/*
 * German A1 word bank for the flashcard app (index.html).
 *
 * HOW TO ADD A WORD — copy any line below and edit it. Fields:
 *   de        German word or phrase. Nouns WITHOUT the article ("Tisch").
 *   article   Nouns only: "der" | "die" | "das". Leave out for other types.
 *   plural    Nouns only: the full plural form ("Tische").
 *             Use "—" if the noun normally has no plural (e.g. "Milch"),
 *             and "Pl." if the noun only exists in the plural (e.g. "Eltern").
 *   en        English meaning.
 *   type      noun | verb | adjective | adverb | phrase | number | question | other
 *   theme     greetings | family | body | food | home | city | travel | shopping |
 *             work | school | time | numbers | weather | leisure | colours | everyday
 *             (a new theme name will simply show up in the filter list)
 *   ex / exEn Short A1 example sentence and its English translation.
 *
 * Progress is stored per German word + article, so editing the English text or
 * the example keeps your progress; renaming the German word starts it fresh.
 */
window.WORDS = [
// ───────── Greetings & phrases ─────────
{de:"Hallo", en:"hello", type:"phrase", theme:"greetings", ex:"Hallo, ich bin Anna.", exEn:"Hello, I am Anna."},
{de:"Guten Morgen", en:"good morning", type:"phrase", theme:"greetings", ex:"Guten Morgen, Frau Müller!", exEn:"Good morning, Mrs Müller!"},
{de:"Guten Tag", en:"hello / good day", type:"phrase", theme:"greetings", ex:"Guten Tag, wie kann ich helfen?", exEn:"Hello, how can I help?"},
{de:"Guten Abend", en:"good evening", type:"phrase", theme:"greetings", ex:"Guten Abend, Herr Schmidt!", exEn:"Good evening, Mr Schmidt!"},
{de:"Gute Nacht", en:"good night", type:"phrase", theme:"greetings", ex:"Gute Nacht, schlaf gut!", exEn:"Good night, sleep well!"},
{de:"Tschüss", en:"bye", type:"phrase", theme:"greetings", ex:"Tschüss, bis morgen!", exEn:"Bye, see you tomorrow!"},
{de:"Auf Wiedersehen", en:"goodbye", type:"phrase", theme:"greetings", ex:"Auf Wiedersehen und danke!", exEn:"Goodbye and thank you!"},
{de:"Bis später", en:"see you later", type:"phrase", theme:"greetings", ex:"Ich muss los. Bis später!", exEn:"I have to go. See you later!"},
{de:"Wie geht's?", en:"how are you? (informal)", type:"phrase", theme:"greetings", ex:"Hallo Tom, wie geht's?", exEn:"Hi Tom, how are you?"},
{de:"Danke", en:"thank you", type:"phrase", theme:"greetings", ex:"Danke, das ist sehr nett!", exEn:"Thank you, that is very kind!"},
{de:"Vielen Dank", en:"thank you very much", type:"phrase", theme:"greetings", ex:"Vielen Dank für Ihre Hilfe!", exEn:"Thank you very much for your help!"},
{de:"Bitte", en:"please; you're welcome", type:"phrase", theme:"greetings", ex:"Einen Kaffee, bitte.", exEn:"A coffee, please."},
{de:"Entschuldigung", en:"excuse me; sorry", type:"phrase", theme:"greetings", ex:"Entschuldigung, wo ist der Bahnhof?", exEn:"Excuse me, where is the station?"},
{de:"Es tut mir leid.", en:"I'm sorry.", type:"phrase", theme:"greetings", ex:"Es tut mir leid, ich bin zu spät.", exEn:"I'm sorry, I'm late."},
{de:"Ja", en:"yes", type:"other", theme:"greetings", ex:"Ja, das ist richtig.", exEn:"Yes, that is right."},
{de:"Nein", en:"no", type:"other", theme:"greetings", ex:"Nein, ich habe keine Zeit.", exEn:"No, I don't have time."},
{de:"Wie heißen Sie?", en:"what is your name? (formal)", type:"phrase", theme:"greetings", ex:"Guten Tag! Wie heißen Sie?", exEn:"Hello! What is your name?"},
{de:"Ich heiße …", en:"my name is …", type:"phrase", theme:"greetings", ex:"Ich heiße Paul Meier.", exEn:"My name is Paul Meier."},
{de:"Woher kommen Sie?", en:"where are you from? (formal)", type:"phrase", theme:"greetings", ex:"Woher kommen Sie? – Aus Spanien.", exEn:"Where are you from? – From Spain."},
{de:"Ich komme aus …", en:"I come from …", type:"phrase", theme:"greetings", ex:"Ich komme aus Indien.", exEn:"I come from India."},
{de:"Freut mich.", en:"nice to meet you", type:"phrase", theme:"greetings", ex:"Ich bin Lisa. – Freut mich!", exEn:"I'm Lisa. – Nice to meet you!"},
{de:"Herzlichen Glückwunsch!", en:"congratulations!", type:"phrase", theme:"greetings", ex:"Herzlichen Glückwunsch zum Geburtstag!", exEn:"Happy birthday!"},
{de:"Viel Glück!", en:"good luck!", type:"phrase", theme:"greetings", ex:"Morgen ist dein Test? Viel Glück!", exEn:"Your test is tomorrow? Good luck!"},
{de:"Guten Appetit!", en:"enjoy your meal!", type:"phrase", theme:"greetings", ex:"Das Essen ist fertig. Guten Appetit!", exEn:"The food is ready. Enjoy your meal!"},
{de:"Prost!", en:"cheers!", type:"phrase", theme:"greetings", ex:"Prost! Auf deine Gesundheit!", exEn:"Cheers! To your health!"},
{de:"Wie bitte?", en:"pardon? / sorry?", type:"phrase", theme:"greetings", ex:"Wie bitte? Können Sie das noch einmal sagen?", exEn:"Pardon? Can you say that again?"},
{de:"Ich verstehe das nicht.", en:"I don't understand that.", type:"phrase", theme:"greetings", ex:"Entschuldigung, ich verstehe das nicht.", exEn:"Sorry, I don't understand that."},
{de:"Sprechen Sie Englisch?", en:"do you speak English?", type:"phrase", theme:"greetings", ex:"Entschuldigung, sprechen Sie Englisch?", exEn:"Excuse me, do you speak English?"},
{de:"Wie viel kostet das?", en:"how much does that cost?", type:"phrase", theme:"greetings", ex:"Die Jacke ist schön. Wie viel kostet das?", exEn:"The jacket is nice. How much does it cost?"},
{de:"Wie spät ist es?", en:"what time is it?", type:"phrase", theme:"greetings", ex:"Wie spät ist es? – Es ist drei Uhr.", exEn:"What time is it? – It is three o'clock."},
{de:"Schönes Wochenende!", en:"have a nice weekend!", type:"phrase", theme:"greetings", ex:"Tschüss und schönes Wochenende!", exEn:"Bye and have a nice weekend!"},
{de:"Alles klar.", en:"all right / got it", type:"phrase", theme:"greetings", ex:"Wir treffen uns um acht. – Alles klar!", exEn:"We'll meet at eight. – All right!"},
{de:"Ich hätte gern …", en:"I would like …", type:"phrase", theme:"greetings", ex:"Ich hätte gern ein Brötchen.", exEn:"I would like a bread roll."},
{de:"Die Rechnung, bitte.", en:"the bill, please", type:"phrase", theme:"greetings", ex:"Entschuldigung, die Rechnung, bitte!", exEn:"Excuse me, the bill, please!"},
{de:"zu Hause", en:"at home", type:"phrase", theme:"greetings", ex:"Heute Abend bin ich zu Hause.", exEn:"I'm at home this evening."},
{de:"nach Hause", en:"(to) home", type:"phrase", theme:"greetings", ex:"Ich gehe jetzt nach Hause.", exEn:"I'm going home now."},
{de:"ein bisschen", en:"a little", type:"phrase", theme:"greetings", ex:"Ich spreche ein bisschen Deutsch.", exEn:"I speak a little German."},

// ───────── Family & people ─────────
{de:"Mann", article:"der", plural:"Männer", en:"man; husband", type:"noun", theme:"family", ex:"Der Mann dort ist mein Lehrer.", exEn:"The man over there is my teacher."},
{de:"Frau", article:"die", plural:"Frauen", en:"woman; wife; Mrs", type:"noun", theme:"family", ex:"Meine Frau arbeitet in einer Bank.", exEn:"My wife works in a bank."},
{de:"Kind", article:"das", plural:"Kinder", en:"child", type:"noun", theme:"family", ex:"Wir haben zwei Kinder.", exEn:"We have two children."},
{de:"Junge", article:"der", plural:"Jungen", en:"boy", type:"noun", theme:"family", ex:"Der Junge ist zehn Jahre alt.", exEn:"The boy is ten years old."},
{de:"Mädchen", article:"das", plural:"Mädchen", en:"girl", type:"noun", theme:"family", ex:"Das Mädchen heißt Emma.", exEn:"The girl is called Emma."},
{de:"Familie", article:"die", plural:"Familien", en:"family", type:"noun", theme:"family", ex:"Meine Familie ist groß.", exEn:"My family is big."},
{de:"Eltern", article:"die", plural:"Pl.", en:"parents", type:"noun", theme:"family", ex:"Meine Eltern wohnen in Hamburg.", exEn:"My parents live in Hamburg."},
{de:"Vater", article:"der", plural:"Väter", en:"father", type:"noun", theme:"family", ex:"Mein Vater ist Arzt.", exEn:"My father is a doctor."},
{de:"Mutter", article:"die", plural:"Mütter", en:"mother", type:"noun", theme:"family", ex:"Meine Mutter kocht gern.", exEn:"My mother likes cooking."},
{de:"Sohn", article:"der", plural:"Söhne", en:"son", type:"noun", theme:"family", ex:"Ihr Sohn ist fünf Jahre alt.", exEn:"Her son is five years old."},
{de:"Tochter", article:"die", plural:"Töchter", en:"daughter", type:"noun", theme:"family", ex:"Unsere Tochter geht in die Schule.", exEn:"Our daughter goes to school."},
{de:"Bruder", article:"der", plural:"Brüder", en:"brother", type:"noun", theme:"family", ex:"Ich habe einen Bruder.", exEn:"I have a brother."},
{de:"Schwester", article:"die", plural:"Schwestern", en:"sister", type:"noun", theme:"family", ex:"Meine Schwester ist 20.", exEn:"My sister is 20."},
{de:"Geschwister", article:"die", plural:"Pl.", en:"siblings", type:"noun", theme:"family", ex:"Hast du Geschwister?", exEn:"Do you have siblings?"},
{de:"Großvater", article:"der", plural:"Großväter", en:"grandfather", type:"noun", theme:"family", ex:"Mein Großvater war Lehrer.", exEn:"My grandfather was a teacher."},
{de:"Großmutter", article:"die", plural:"Großmütter", en:"grandmother", type:"noun", theme:"family", ex:"Die Großmutter wohnt auf dem Land.", exEn:"The grandmother lives in the countryside."},
{de:"Großeltern", article:"die", plural:"Pl.", en:"grandparents", type:"noun", theme:"family", ex:"Am Sonntag besuchen wir die Großeltern.", exEn:"On Sunday we visit the grandparents."},
{de:"Opa", article:"der", plural:"Opas", en:"grandpa", type:"noun", theme:"family", ex:"Opa liest gern Zeitung.", exEn:"Grandpa likes reading the newspaper."},
{de:"Oma", article:"die", plural:"Omas", en:"grandma", type:"noun", theme:"family", ex:"Meine Oma wohnt bei uns.", exEn:"My grandma lives with us."},
{de:"Onkel", article:"der", plural:"Onkel", en:"uncle", type:"noun", theme:"family", ex:"Mein Onkel wohnt in Wien.", exEn:"My uncle lives in Vienna."},
{de:"Tante", article:"die", plural:"Tanten", en:"aunt", type:"noun", theme:"family", ex:"Meine Tante hat drei Kinder.", exEn:"My aunt has three children."},
{de:"Freund", article:"der", plural:"Freunde", en:"friend; boyfriend", type:"noun", theme:"family", ex:"Das ist mein Freund Max.", exEn:"This is my friend Max."},
{de:"Freundin", article:"die", plural:"Freundinnen", en:"friend (female); girlfriend", type:"noun", theme:"family", ex:"Meine Freundin kommt aus Italien.", exEn:"My friend comes from Italy."},
{de:"Nachbar", article:"der", plural:"Nachbarn", en:"neighbour", type:"noun", theme:"family", ex:"Unser Nachbar hat einen Hund.", exEn:"Our neighbour has a dog."},
{de:"Mensch", article:"der", plural:"Menschen", en:"person; human being", type:"noun", theme:"family", ex:"In Berlin leben viele Menschen.", exEn:"Many people live in Berlin."},
{de:"Leute", article:"die", plural:"Pl.", en:"people", type:"noun", theme:"family", ex:"Viele Leute warten auf den Bus.", exEn:"Many people are waiting for the bus."},
{de:"Person", article:"die", plural:"Personen", en:"person", type:"noun", theme:"family", ex:"Das Zimmer ist für zwei Personen.", exEn:"The room is for two people."},
{de:"Herr", article:"der", plural:"Herren", en:"Mr; gentleman", type:"noun", theme:"family", ex:"Guten Tag, Herr Becker!", exEn:"Hello, Mr Becker!"},
{de:"Name", article:"der", plural:"Namen", en:"name", type:"noun", theme:"family", ex:"Mein Name ist Ali.", exEn:"My name is Ali."},
{de:"Vorname", article:"der", plural:"Vornamen", en:"first name", type:"noun", theme:"family", ex:"Wie ist Ihr Vorname?", exEn:"What is your first name?"},
{de:"Familienname", article:"der", plural:"Familiennamen", en:"surname", type:"noun", theme:"family", ex:"Mein Familienname ist Schneider.", exEn:"My surname is Schneider."},
{de:"Alter", article:"das", plural:"—", en:"age", type:"noun", theme:"family", ex:"Bitte schreiben Sie Ihr Alter hier.", exEn:"Please write your age here."},
{de:"Geburtstag", article:"der", plural:"Geburtstage", en:"birthday", type:"noun", theme:"family", ex:"Wann hast du Geburtstag?", exEn:"When is your birthday?"},
{de:"Hochzeit", article:"die", plural:"Hochzeiten", en:"wedding", type:"noun", theme:"family", ex:"Die Hochzeit ist im Juni.", exEn:"The wedding is in June."},
{de:"Adresse", article:"die", plural:"Adressen", en:"address", type:"noun", theme:"family", ex:"Wie ist Ihre Adresse?", exEn:"What is your address?"},
{de:"Telefonnummer", article:"die", plural:"Telefonnummern", en:"phone number", type:"noun", theme:"family", ex:"Wie ist deine Telefonnummer?", exEn:"What is your phone number?"},
{de:"E-Mail", article:"die", plural:"E-Mails", en:"email", type:"noun", theme:"family", ex:"Ich schreibe dir eine E-Mail.", exEn:"I'll write you an email."},
{de:"Land", article:"das", plural:"Länder", en:"country; countryside", type:"noun", theme:"family", ex:"Deutschland ist ein schönes Land.", exEn:"Germany is a beautiful country."},
{de:"Sprache", article:"die", plural:"Sprachen", en:"language", type:"noun", theme:"family", ex:"Ich spreche drei Sprachen.", exEn:"I speak three languages."},
{de:"Gast", article:"der", plural:"Gäste", en:"guest", type:"noun", theme:"family", ex:"Wir haben heute Gäste.", exEn:"We have guests today."},
{de:"ledig", en:"single (not married)", type:"adjective", theme:"family", ex:"Ich bin ledig.", exEn:"I am single."},
{de:"verheiratet", en:"married", type:"adjective", theme:"family", ex:"Sind Sie verheiratet?", exEn:"Are you married?"},
{de:"heiraten", en:"to marry", type:"verb", theme:"family", ex:"Wir heiraten im Sommer.", exEn:"We are getting married in the summer."},
{de:"kennenlernen", en:"to get to know; to meet", type:"verb", theme:"family", ex:"Ich möchte neue Leute kennenlernen.", exEn:"I would like to meet new people."},

// ───────── Body & health ─────────
{de:"Körper", article:"der", plural:"Körper", en:"body", type:"noun", theme:"body", ex:"Sport ist gut für den Körper.", exEn:"Sport is good for the body."},
{de:"Kopf", article:"der", plural:"Köpfe", en:"head", type:"noun", theme:"body", ex:"Er schüttelt den Kopf.", exEn:"He shakes his head."},
{de:"Gesicht", article:"das", plural:"Gesichter", en:"face", type:"noun", theme:"body", ex:"Sie hat ein schönes Gesicht.", exEn:"She has a beautiful face."},
{de:"Auge", article:"das", plural:"Augen", en:"eye", type:"noun", theme:"body", ex:"Er hat blaue Augen.", exEn:"He has blue eyes."},
{de:"Ohr", article:"das", plural:"Ohren", en:"ear", type:"noun", theme:"body", ex:"Das Baby hat kleine Ohren.", exEn:"The baby has small ears."},
{de:"Nase", article:"die", plural:"Nasen", en:"nose", type:"noun", theme:"body", ex:"Meine Nase ist kalt.", exEn:"My nose is cold."},
{de:"Mund", article:"der", plural:"Münder", en:"mouth", type:"noun", theme:"body", ex:"Mach bitte den Mund auf.", exEn:"Please open your mouth."},
{de:"Zahn", article:"der", plural:"Zähne", en:"tooth", type:"noun", theme:"body", ex:"Ich putze meine Zähne.", exEn:"I brush my teeth."},
{de:"Haar", article:"das", plural:"Haare", en:"hair", type:"noun", theme:"body", ex:"Sie hat lange Haare.", exEn:"She has long hair."},
{de:"Arm", article:"der", plural:"Arme", en:"arm", type:"noun", theme:"body", ex:"Sie nimmt das Baby auf den Arm.", exEn:"She picks the baby up in her arms."},
{de:"Hand", article:"die", plural:"Hände", en:"hand", type:"noun", theme:"body", ex:"Wasch dir bitte die Hände!", exEn:"Please wash your hands!"},
{de:"Bauch", article:"der", plural:"Bäuche", en:"belly; stomach", type:"noun", theme:"body", ex:"Ich habe Bauchschmerzen.", exEn:"I have a stomach ache."},
{de:"Rücken", article:"der", plural:"Rücken", en:"back", type:"noun", theme:"body", ex:"Mein Rücken tut weh.", exEn:"My back hurts."},
{de:"Bein", article:"das", plural:"Beine", en:"leg", type:"noun", theme:"body", ex:"Der Hund hat vier Beine.", exEn:"The dog has four legs."},
{de:"Fuß", article:"der", plural:"Füße", en:"foot", type:"noun", theme:"body", ex:"Ich gehe zu Fuß.", exEn:"I walk (go on foot)."},
{de:"Arzt", article:"der", plural:"Ärzte", en:"doctor (male)", type:"noun", theme:"body", ex:"Ich muss zum Arzt.", exEn:"I have to go to the doctor."},
{de:"Apotheke", article:"die", plural:"Apotheken", en:"pharmacy", type:"noun", theme:"body", ex:"Wo ist die nächste Apotheke?", exEn:"Where is the nearest pharmacy?"},
{de:"Krankenhaus", article:"das", plural:"Krankenhäuser", en:"hospital", type:"noun", theme:"body", ex:"Er liegt im Krankenhaus.", exEn:"He is in hospital."},
{de:"Medikament", article:"das", plural:"Medikamente", en:"medicine", type:"noun", theme:"body", ex:"Nehmen Sie das Medikament dreimal am Tag.", exEn:"Take the medicine three times a day."},
{de:"Tablette", article:"die", plural:"Tabletten", en:"tablet; pill", type:"noun", theme:"body", ex:"Ich brauche eine Tablette gegen Kopfschmerzen.", exEn:"I need a pill for my headache."},
{de:"Fieber", article:"das", plural:"—", en:"fever", type:"noun", theme:"body", ex:"Das Kind hat Fieber.", exEn:"The child has a fever."},
{de:"Schmerz", article:"der", plural:"Schmerzen", en:"pain", type:"noun", theme:"body", ex:"Wo haben Sie Schmerzen?", exEn:"Where does it hurt?"},
{de:"Erkältung", article:"die", plural:"Erkältungen", en:"cold (illness)", type:"noun", theme:"body", ex:"Ich habe eine Erkältung.", exEn:"I have a cold."},
{de:"Gesundheit", article:"die", plural:"—", en:"health; bless you!", type:"noun", theme:"body", ex:"Hatschi! – Gesundheit!", exEn:"Achoo! – Bless you!"},
{de:"Hilfe", article:"die", plural:"—", en:"help", type:"noun", theme:"body", ex:"Ich brauche Hilfe.", exEn:"I need help."},
{de:"krank", en:"ill; sick", type:"adjective", theme:"body", ex:"Ich bin heute krank.", exEn:"I am ill today."},
{de:"gesund", en:"healthy", type:"adjective", theme:"body", ex:"Gemüse ist gesund.", exEn:"Vegetables are healthy."},
{de:"müde", en:"tired", type:"adjective", theme:"body", ex:"Ich bin sehr müde.", exEn:"I am very tired."},
{de:"wehtun", en:"to hurt", type:"verb", theme:"body", ex:"Mein Kopf tut weh.", exEn:"My head hurts."},
{de:"duschen", en:"to shower", type:"verb", theme:"body", ex:"Ich dusche jeden Morgen.", exEn:"I shower every morning."},

// ───────── Food & drink ─────────
{de:"Essen", article:"das", plural:"Essen", en:"food; meal", type:"noun", theme:"food", ex:"Das Essen ist sehr gut.", exEn:"The food is very good."},
{de:"Getränk", article:"das", plural:"Getränke", en:"drink", type:"noun", theme:"food", ex:"Möchten Sie ein Getränk?", exEn:"Would you like a drink?"},
{de:"Wasser", article:"das", plural:"—", en:"water", type:"noun", theme:"food", ex:"Ein Glas Wasser, bitte.", exEn:"A glass of water, please."},
{de:"Kaffee", article:"der", plural:"Kaffees", en:"coffee", type:"noun", theme:"food", ex:"Ich trinke morgens Kaffee.", exEn:"I drink coffee in the morning."},
{de:"Tee", article:"der", plural:"Tees", en:"tea", type:"noun", theme:"food", ex:"Möchtest du Tee oder Kaffee?", exEn:"Would you like tea or coffee?"},
{de:"Milch", article:"die", plural:"—", en:"milk", type:"noun", theme:"food", ex:"Ich trinke Kaffee mit Milch.", exEn:"I drink coffee with milk."},
{de:"Saft", article:"der", plural:"Säfte", en:"juice", type:"noun", theme:"food", ex:"Die Kinder trinken Apfelsaft.", exEn:"The children are drinking apple juice."},
{de:"Bier", article:"das", plural:"Biere", en:"beer", type:"noun", theme:"food", ex:"Ein Bier, bitte!", exEn:"A beer, please!"},
{de:"Wein", article:"der", plural:"Weine", en:"wine", type:"noun", theme:"food", ex:"Möchten Sie Rotwein oder Weißwein?", exEn:"Would you like red wine or white wine?"},
{de:"Brot", article:"das", plural:"Brote", en:"bread", type:"noun", theme:"food", ex:"Wir kaufen Brot beim Bäcker.", exEn:"We buy bread at the baker's."},
{de:"Brötchen", article:"das", plural:"Brötchen", en:"bread roll", type:"noun", theme:"food", ex:"Zum Frühstück esse ich zwei Brötchen.", exEn:"For breakfast I eat two bread rolls."},
{de:"Butter", article:"die", plural:"—", en:"butter", type:"noun", theme:"food", ex:"Ich esse Brot mit Butter.", exEn:"I eat bread with butter."},
{de:"Käse", article:"der", plural:"—", en:"cheese", type:"noun", theme:"food", ex:"Ich möchte 200 Gramm Käse.", exEn:"I would like 200 grams of cheese."},
{de:"Wurst", article:"die", plural:"Würste", en:"sausage; cold cuts", type:"noun", theme:"food", ex:"In Deutschland isst man viel Wurst.", exEn:"People eat a lot of sausage in Germany."},
{de:"Ei", article:"das", plural:"Eier", en:"egg", type:"noun", theme:"food", ex:"Wir brauchen zehn Eier.", exEn:"We need ten eggs."},
{de:"Fleisch", article:"das", plural:"—", en:"meat", type:"noun", theme:"food", ex:"Ich esse kein Fleisch.", exEn:"I don't eat meat."},
{de:"Fisch", article:"der", plural:"Fische", en:"fish", type:"noun", theme:"food", ex:"Am Freitag essen wir Fisch.", exEn:"On Friday we eat fish."},
{de:"Gemüse", article:"das", plural:"—", en:"vegetables", type:"noun", theme:"food", ex:"Ich koche eine Suppe mit Gemüse.", exEn:"I'm making a vegetable soup."},
{de:"Obst", article:"das", plural:"—", en:"fruit", type:"noun", theme:"food", ex:"Ich kaufe Obst auf dem Markt.", exEn:"I buy fruit at the market."},
{de:"Apfel", article:"der", plural:"Äpfel", en:"apple", type:"noun", theme:"food", ex:"Ich esse jeden Tag einen Apfel.", exEn:"I eat an apple every day."},
{de:"Banane", article:"die", plural:"Bananen", en:"banana", type:"noun", theme:"food", ex:"Das Kind isst eine Banane.", exEn:"The child is eating a banana."},
{de:"Orange", article:"die", plural:"Orangen", en:"orange", type:"noun", theme:"food", ex:"Ich esse eine Orange.", exEn:"I'm eating an orange."},
{de:"Tomate", article:"die", plural:"Tomaten", en:"tomato", type:"noun", theme:"food", ex:"Ich mache einen Salat mit Tomaten.", exEn:"I'm making a salad with tomatoes."},
{de:"Kartoffel", article:"die", plural:"Kartoffeln", en:"potato", type:"noun", theme:"food", ex:"Zum Fleisch gibt es Kartoffeln.", exEn:"There are potatoes with the meat."},
{de:"Salat", article:"der", plural:"Salate", en:"salad; lettuce", type:"noun", theme:"food", ex:"Ich nehme einen Salat.", exEn:"I'll have a salad."},
{de:"Reis", article:"der", plural:"—", en:"rice", type:"noun", theme:"food", ex:"Ich esse gern Reis mit Gemüse.", exEn:"I like eating rice with vegetables."},
{de:"Nudel", article:"die", plural:"Nudeln", en:"noodle; pasta", type:"noun", theme:"food", ex:"Die Kinder essen gern Nudeln.", exEn:"The children like eating pasta."},
{de:"Pizza", article:"die", plural:"Pizzas / Pizzen", en:"pizza", type:"noun", theme:"food", ex:"Wir bestellen eine Pizza.", exEn:"We're ordering a pizza."},
{de:"Suppe", article:"die", plural:"Suppen", en:"soup", type:"noun", theme:"food", ex:"Die Suppe ist zu heiß.", exEn:"The soup is too hot."},
{de:"Kuchen", article:"der", plural:"Kuchen", en:"cake", type:"noun", theme:"food", ex:"Möchtest du ein Stück Kuchen?", exEn:"Would you like a piece of cake?"},
{de:"Schokolade", article:"die", plural:"Schokoladen", en:"chocolate", type:"noun", theme:"food", ex:"Ich esse gern Schokolade.", exEn:"I like eating chocolate."},
{de:"Eis", article:"das", plural:"—", en:"ice cream; ice", type:"noun", theme:"food", ex:"Im Sommer essen wir viel Eis.", exEn:"In summer we eat a lot of ice cream."},
{de:"Zucker", article:"der", plural:"—", en:"sugar", type:"noun", theme:"food", ex:"Nehmen Sie Zucker in den Kaffee?", exEn:"Do you take sugar in your coffee?"},
{de:"Salz", article:"das", plural:"—", en:"salt", type:"noun", theme:"food", ex:"Die Suppe braucht mehr Salz.", exEn:"The soup needs more salt."},
{de:"Frühstück", article:"das", plural:"Frühstücke", en:"breakfast", type:"noun", theme:"food", ex:"Das Frühstück ist um acht Uhr.", exEn:"Breakfast is at eight o'clock."},
{de:"Mittagessen", article:"das", plural:"Mittagessen", en:"lunch", type:"noun", theme:"food", ex:"Was gibt es zum Mittagessen?", exEn:"What's for lunch?"},
{de:"Abendessen", article:"das", plural:"Abendessen", en:"dinner", type:"noun", theme:"food", ex:"Zum Abendessen gibt es Suppe.", exEn:"There is soup for dinner."},
{de:"Restaurant", article:"das", plural:"Restaurants", en:"restaurant", type:"noun", theme:"food", ex:"Wir gehen heute ins Restaurant.", exEn:"We're going to a restaurant today."},
{de:"Café", article:"das", plural:"Cafés", en:"café", type:"noun", theme:"food", ex:"Treffen wir uns im Café?", exEn:"Shall we meet at the café?"},
{de:"Speisekarte", article:"die", plural:"Speisekarten", en:"menu", type:"noun", theme:"food", ex:"Die Speisekarte, bitte.", exEn:"The menu, please."},
{de:"Rechnung", article:"die", plural:"Rechnungen", en:"bill; invoice", type:"noun", theme:"food", ex:"Die Rechnung ist sehr hoch.", exEn:"The bill is very high."},
{de:"Teller", article:"der", plural:"Teller", en:"plate", type:"noun", theme:"food", ex:"Die Teller sind im Schrank.", exEn:"The plates are in the cupboard."},
{de:"Tasse", article:"die", plural:"Tassen", en:"cup", type:"noun", theme:"food", ex:"Eine Tasse Kaffee, bitte.", exEn:"A cup of coffee, please."},
{de:"Glas", article:"das", plural:"Gläser", en:"glass", type:"noun", theme:"food", ex:"Ich trinke ein Glas Wein.", exEn:"I'm drinking a glass of wine."},
{de:"Flasche", article:"die", plural:"Flaschen", en:"bottle", type:"noun", theme:"food", ex:"Eine Flasche Wasser kostet einen Euro.", exEn:"A bottle of water costs one euro."},
{de:"Kellner", article:"der", plural:"Kellner", en:"waiter", type:"noun", theme:"food", ex:"Der Kellner bringt das Essen.", exEn:"The waiter brings the food."},
{de:"Hunger", article:"der", plural:"—", en:"hunger", type:"noun", theme:"food", ex:"Ich habe Hunger.", exEn:"I am hungry."},
{de:"Durst", article:"der", plural:"—", en:"thirst", type:"noun", theme:"food", ex:"Hast du Durst?", exEn:"Are you thirsty?"},
{de:"Stück", article:"das", plural:"Stücke", en:"piece", type:"noun", theme:"food", ex:"Ich nehme ein Stück Pizza.", exEn:"I'll have a piece of pizza."},
{de:"Kilo", article:"das", plural:"Kilos", en:"kilo", type:"noun", theme:"food", ex:"Ein Kilo Äpfel kostet zwei Euro.", exEn:"A kilo of apples costs two euros."},
{de:"Liter", article:"der", plural:"Liter", en:"litre", type:"noun", theme:"food", ex:"Ich kaufe einen Liter Milch.", exEn:"I'm buying a litre of milk."},
{de:"Gramm", article:"das", plural:"Gramm", en:"gram", type:"noun", theme:"food", ex:"Ich brauche 500 Gramm Mehl.", exEn:"I need 500 grams of flour."},
{de:"Bäckerei", article:"die", plural:"Bäckereien", en:"bakery", type:"noun", theme:"food", ex:"Die Bäckerei öffnet um sechs Uhr.", exEn:"The bakery opens at six o'clock."},
{de:"lecker", en:"tasty; delicious", type:"adjective", theme:"food", ex:"Die Pizza ist lecker!", exEn:"The pizza is delicious!"},
{de:"süß", en:"sweet; cute", type:"adjective", theme:"food", ex:"Der Kuchen ist sehr süß.", exEn:"The cake is very sweet."},
{de:"scharf", en:"spicy; sharp", type:"adjective", theme:"food", ex:"Das Essen ist sehr scharf.", exEn:"The food is very spicy."},
{de:"frisch", en:"fresh", type:"adjective", theme:"food", ex:"Das Brot ist ganz frisch.", exEn:"The bread is really fresh."},
{de:"essen", en:"to eat", type:"verb", theme:"food", ex:"Wir essen um zwölf Uhr.", exEn:"We eat at twelve o'clock."},
{de:"trinken", en:"to drink", type:"verb", theme:"food", ex:"Was möchtest du trinken?", exEn:"What would you like to drink?"},
{de:"kochen", en:"to cook", type:"verb", theme:"food", ex:"Ich koche heute Abend.", exEn:"I'm cooking tonight."},
{de:"frühstücken", en:"to have breakfast", type:"verb", theme:"food", ex:"Ich frühstücke um sieben Uhr.", exEn:"I have breakfast at seven o'clock."},
{de:"bestellen", en:"to order", type:"verb", theme:"food", ex:"Ich möchte bitte bestellen.", exEn:"I would like to order, please."},
{de:"bezahlen", en:"to pay", type:"verb", theme:"food", ex:"Ich bezahle mit Karte.", exEn:"I'm paying by card."},
{de:"schmecken", en:"to taste", type:"verb", theme:"food", ex:"Schmeckt es dir?", exEn:"Do you like it? (the food)"},

// ───────── Home ─────────
{de:"Haus", article:"das", plural:"Häuser", en:"house", type:"noun", theme:"home", ex:"Das Haus hat einen Garten.", exEn:"The house has a garden."},
{de:"Wohnung", article:"die", plural:"Wohnungen", en:"flat; apartment", type:"noun", theme:"home", ex:"Die Wohnung hat drei Zimmer.", exEn:"The flat has three rooms."},
{de:"Zimmer", article:"das", plural:"Zimmer", en:"room", type:"noun", theme:"home", ex:"Mein Zimmer ist klein.", exEn:"My room is small."},
{de:"Wohnzimmer", article:"das", plural:"Wohnzimmer", en:"living room", type:"noun", theme:"home", ex:"Der Fernseher steht im Wohnzimmer.", exEn:"The TV is in the living room."},
{de:"Schlafzimmer", article:"das", plural:"Schlafzimmer", en:"bedroom", type:"noun", theme:"home", ex:"Das Schlafzimmer ist ruhig.", exEn:"The bedroom is quiet."},
{de:"Küche", article:"die", plural:"Küchen", en:"kitchen", type:"noun", theme:"home", ex:"Die Küche ist sehr modern.", exEn:"The kitchen is very modern."},
{de:"Bad", article:"das", plural:"Bäder", en:"bathroom; bath", type:"noun", theme:"home", ex:"Das Bad hat eine Dusche.", exEn:"The bathroom has a shower."},
{de:"Toilette", article:"die", plural:"Toiletten", en:"toilet", type:"noun", theme:"home", ex:"Die Toilette ist links.", exEn:"The toilet is on the left."},
{de:"Balkon", article:"der", plural:"Balkone", en:"balcony", type:"noun", theme:"home", ex:"Die Wohnung hat einen Balkon.", exEn:"The flat has a balcony."},
{de:"Garten", article:"der", plural:"Gärten", en:"garden", type:"noun", theme:"home", ex:"Der Garten ist sehr groß.", exEn:"The garden is very big."},
{de:"Aufzug", article:"der", plural:"Aufzüge", en:"lift; elevator", type:"noun", theme:"home", ex:"Der Aufzug ist kaputt.", exEn:"The lift is broken."},
{de:"Tür", article:"die", plural:"Türen", en:"door", type:"noun", theme:"home", ex:"Bitte schließen Sie die Tür.", exEn:"Please close the door."},
{de:"Fenster", article:"das", plural:"Fenster", en:"window", type:"noun", theme:"home", ex:"Kannst du das Fenster öffnen?", exEn:"Can you open the window?"},
{de:"Miete", article:"die", plural:"Mieten", en:"rent", type:"noun", theme:"home", ex:"Die Miete ist 800 Euro im Monat.", exEn:"The rent is 800 euros a month."},
{de:"Möbel", article:"die", plural:"Pl.", en:"furniture", type:"noun", theme:"home", ex:"Die Möbel sind neu.", exEn:"The furniture is new."},
{de:"Tisch", article:"der", plural:"Tische", en:"table", type:"noun", theme:"home", ex:"Das Essen steht auf dem Tisch.", exEn:"The food is on the table."},
{de:"Stuhl", article:"der", plural:"Stühle", en:"chair", type:"noun", theme:"home", ex:"Der Stuhl ist bequem.", exEn:"The chair is comfortable."},
{de:"Sofa", article:"das", plural:"Sofas", en:"sofa", type:"noun", theme:"home", ex:"Die Katze schläft auf dem Sofa.", exEn:"The cat is sleeping on the sofa."},
{de:"Bett", article:"das", plural:"Betten", en:"bed", type:"noun", theme:"home", ex:"Ich gehe um elf Uhr ins Bett.", exEn:"I go to bed at eleven o'clock."},
{de:"Schrank", article:"der", plural:"Schränke", en:"cupboard; wardrobe", type:"noun", theme:"home", ex:"Die Kleidung ist im Schrank.", exEn:"The clothes are in the wardrobe."},
{de:"Lampe", article:"die", plural:"Lampen", en:"lamp", type:"noun", theme:"home", ex:"Die Lampe ist sehr hell.", exEn:"The lamp is very bright."},
{de:"Kühlschrank", article:"der", plural:"Kühlschränke", en:"fridge", type:"noun", theme:"home", ex:"Die Milch ist im Kühlschrank.", exEn:"The milk is in the fridge."},
{de:"Dusche", article:"die", plural:"Duschen", en:"shower", type:"noun", theme:"home", ex:"Die Dusche ist kaputt.", exEn:"The shower is broken."},
{de:"Schlüssel", article:"der", plural:"Schlüssel", en:"key", type:"noun", theme:"home", ex:"Ich finde meinen Schlüssel nicht.", exEn:"I can't find my key."},
{de:"Licht", article:"das", plural:"Lichter", en:"light", type:"noun", theme:"home", ex:"Mach bitte das Licht an.", exEn:"Please switch on the light."},
{de:"Fernseher", article:"der", plural:"Fernseher", en:"television (set)", type:"noun", theme:"home", ex:"Der Fernseher ist neu.", exEn:"The TV is new."},
{de:"Handy", article:"das", plural:"Handys", en:"mobile phone", type:"noun", theme:"home", ex:"Mein Handy ist kaputt.", exEn:"My mobile phone is broken."},
{de:"Telefon", article:"das", plural:"Telefone", en:"telephone", type:"noun", theme:"home", ex:"Das Telefon klingelt.", exEn:"The phone is ringing."},
{de:"Bild", article:"das", plural:"Bilder", en:"picture", type:"noun", theme:"home", ex:"Das Bild ist sehr schön.", exEn:"The picture is very beautiful."},
{de:"Uhr", article:"die", plural:"Uhren", en:"clock; watch; o'clock", type:"noun", theme:"home", ex:"Die Uhr hängt in der Küche.", exEn:"The clock is hanging in the kitchen."},
{de:"Buch", article:"das", plural:"Bücher", en:"book", type:"noun", theme:"home", ex:"Ich lese ein Buch.", exEn:"I'm reading a book."},
{de:"Zeitung", article:"die", plural:"Zeitungen", en:"newspaper", type:"noun", theme:"home", ex:"Mein Vater liest die Zeitung.", exEn:"My father reads the newspaper."},
{de:"Brief", article:"der", plural:"Briefe", en:"letter", type:"noun", theme:"home", ex:"Ich schreibe einen Brief.", exEn:"I'm writing a letter."},
{de:"Post", article:"die", plural:"—", en:"post office; mail", type:"noun", theme:"home", ex:"Ich gehe zur Post.", exEn:"I'm going to the post office."},
{de:"Paket", article:"das", plural:"Pakete", en:"parcel", type:"noun", theme:"home", ex:"Das Paket kommt morgen.", exEn:"The parcel arrives tomorrow."},
{de:"Nachricht", article:"die", plural:"Nachrichten", en:"message; (pl.) the news", type:"noun", theme:"home", ex:"Ich habe deine Nachricht bekommen.", exEn:"I got your message."},
{de:"wohnen", en:"to live (reside)", type:"verb", theme:"home", ex:"Ich wohne in Frankfurt.", exEn:"I live in Frankfurt."},
{de:"putzen", en:"to clean", type:"verb", theme:"home", ex:"Am Samstag putze ich die Wohnung.", exEn:"On Saturday I clean the flat."},
{de:"waschen", en:"to wash", type:"verb", theme:"home", ex:"Ich wasche meine Kleidung.", exEn:"I wash my clothes."},
{de:"schlafen", en:"to sleep", type:"verb", theme:"home", ex:"Ich schlafe acht Stunden.", exEn:"I sleep eight hours."},
{de:"aufstehen", en:"to get up", type:"verb", theme:"home", ex:"Ich stehe um sechs Uhr auf.", exEn:"I get up at six o'clock."},
{de:"mieten", en:"to rent", type:"verb", theme:"home", ex:"Wir mieten eine Wohnung.", exEn:"We are renting a flat."},
{de:"ruhig", en:"quiet; calm", type:"adjective", theme:"home", ex:"Die Straße ist sehr ruhig.", exEn:"The street is very quiet."},
{de:"laut", en:"loud; noisy", type:"adjective", theme:"home", ex:"Die Musik ist zu laut.", exEn:"The music is too loud."},
{de:"hell", en:"bright; light", type:"adjective", theme:"home", ex:"Die Wohnung ist hell.", exEn:"The flat is bright."},
{de:"dunkel", en:"dark", type:"adjective", theme:"home", ex:"Im Winter ist es früh dunkel.", exEn:"In winter it gets dark early."},
{de:"bequem", en:"comfortable", type:"adjective", theme:"home", ex:"Das Sofa ist sehr bequem.", exEn:"The sofa is very comfortable."},

// ───────── City ─────────
{de:"Stadt", article:"die", plural:"Städte", en:"town; city", type:"noun", theme:"city", ex:"Hamburg ist eine große Stadt.", exEn:"Hamburg is a big city."},
{de:"Dorf", article:"das", plural:"Dörfer", en:"village", type:"noun", theme:"city", ex:"Meine Oma wohnt in einem Dorf.", exEn:"My grandma lives in a village."},
{de:"Straße", article:"die", plural:"Straßen", en:"street; road", type:"noun", theme:"city", ex:"In welcher Straße wohnst du?", exEn:"Which street do you live on?"},
{de:"Platz", article:"der", plural:"Plätze", en:"square; place; seat", type:"noun", theme:"city", ex:"Ist der Platz hier frei?", exEn:"Is this seat free?"},
{de:"Kirche", article:"die", plural:"Kirchen", en:"church", type:"noun", theme:"city", ex:"Die Kirche ist sehr alt.", exEn:"The church is very old."},
{de:"Museum", article:"das", plural:"Museen", en:"museum", type:"noun", theme:"city", ex:"Das Museum ist montags geschlossen.", exEn:"The museum is closed on Mondays."},
{de:"Kino", article:"das", plural:"Kinos", en:"cinema", type:"noun", theme:"city", ex:"Gehen wir heute ins Kino?", exEn:"Shall we go to the cinema today?"},
{de:"Theater", article:"das", plural:"Theater", en:"theatre", type:"noun", theme:"city", ex:"Das Theater ist im Zentrum.", exEn:"The theatre is in the centre."},
{de:"Park", article:"der", plural:"Parks", en:"park", type:"noun", theme:"city", ex:"Der Park ist sehr schön.", exEn:"The park is very beautiful."},
{de:"Bank", article:"die", plural:"Banken", en:"bank", type:"noun", theme:"city", ex:"Ich gehe zur Bank.", exEn:"I'm going to the bank."},
{de:"Polizei", article:"die", plural:"—", en:"police", type:"noun", theme:"city", ex:"Rufen Sie die Polizei!", exEn:"Call the police!"},
{de:"Hotel", article:"das", plural:"Hotels", en:"hotel", type:"noun", theme:"city", ex:"Das Hotel ist in der Nähe vom Bahnhof.", exEn:"The hotel is near the station."},
{de:"Ampel", article:"die", plural:"Ampeln", en:"traffic light", type:"noun", theme:"city", ex:"Warten Sie an der Ampel.", exEn:"Wait at the traffic light."},
{de:"Ecke", article:"die", plural:"Ecken", en:"corner", type:"noun", theme:"city", ex:"Die Bäckerei ist an der Ecke.", exEn:"The bakery is on the corner."},
{de:"Zentrum", article:"das", plural:"Zentren", en:"centre", type:"noun", theme:"city", ex:"Ich wohne im Zentrum.", exEn:"I live in the centre."},
{de:"Haltestelle", article:"die", plural:"Haltestellen", en:"(bus/tram) stop", type:"noun", theme:"city", ex:"Die Haltestelle ist vor dem Haus.", exEn:"The stop is in front of the house."},
{de:"Markt", article:"der", plural:"Märkte", en:"market", type:"noun", theme:"city", ex:"Samstags gehe ich auf den Markt.", exEn:"On Saturdays I go to the market."},
{de:"Weg", article:"der", plural:"Wege", en:"way; path", type:"noun", theme:"city", ex:"Können Sie mir den Weg zeigen?", exEn:"Can you show me the way?"},
{de:"links", en:"left; on the left", type:"adverb", theme:"city", ex:"Gehen Sie hier links.", exEn:"Turn left here."},
{de:"rechts", en:"right; on the right", type:"adverb", theme:"city", ex:"Die Bank ist rechts.", exEn:"The bank is on the right."},
{de:"geradeaus", en:"straight ahead", type:"adverb", theme:"city", ex:"Gehen Sie immer geradeaus.", exEn:"Keep going straight ahead."},
{de:"nah", en:"near; close", type:"adjective", theme:"city", ex:"Der Bahnhof ist ganz nah.", exEn:"The station is very close."},
{de:"weit", en:"far", type:"adjective", theme:"city", ex:"Ist es weit bis zum Zentrum?", exEn:"Is it far to the centre?"},

// ───────── Travel & transport ─────────
{de:"Bahnhof", article:"der", plural:"Bahnhöfe", en:"(train) station", type:"noun", theme:"travel", ex:"Wie komme ich zum Bahnhof?", exEn:"How do I get to the station?"},
{de:"Flughafen", article:"der", plural:"Flughäfen", en:"airport", type:"noun", theme:"travel", ex:"Ich fahre mit dem Taxi zum Flughafen.", exEn:"I'm taking a taxi to the airport."},
{de:"Zug", article:"der", plural:"Züge", en:"train", type:"noun", theme:"travel", ex:"Der Zug fährt um acht Uhr.", exEn:"The train leaves at eight o'clock."},
{de:"Bus", article:"der", plural:"Busse", en:"bus", type:"noun", theme:"travel", ex:"Der Bus kommt gleich.", exEn:"The bus is coming soon."},
{de:"U-Bahn", article:"die", plural:"U-Bahnen", en:"underground; subway", type:"noun", theme:"travel", ex:"Die U-Bahn kommt alle fünf Minuten.", exEn:"The underground comes every five minutes."},
{de:"Auto", article:"das", plural:"Autos", en:"car", type:"noun", theme:"travel", ex:"Wir fahren mit dem Auto nach Italien.", exEn:"We're driving to Italy."},
{de:"Taxi", article:"das", plural:"Taxis", en:"taxi", type:"noun", theme:"travel", ex:"Ich nehme ein Taxi.", exEn:"I'm taking a taxi."},
{de:"Fahrrad", article:"das", plural:"Fahrräder", en:"bicycle", type:"noun", theme:"travel", ex:"Ich fahre mit dem Fahrrad zur Schule.", exEn:"I cycle to school."},
{de:"Flugzeug", article:"das", plural:"Flugzeuge", en:"plane", type:"noun", theme:"travel", ex:"Das Flugzeug landet um 14 Uhr.", exEn:"The plane lands at 2 pm."},
{de:"Fahrkarte", article:"die", plural:"Fahrkarten", en:"ticket (transport)", type:"noun", theme:"travel", ex:"Wo kann ich eine Fahrkarte kaufen?", exEn:"Where can I buy a ticket?"},
{de:"Ticket", article:"das", plural:"Tickets", en:"ticket", type:"noun", theme:"travel", ex:"Hast du schon ein Ticket?", exEn:"Do you already have a ticket?"},
{de:"Fahrplan", article:"der", plural:"Fahrpläne", en:"timetable", type:"noun", theme:"travel", ex:"Der Fahrplan hängt an der Haltestelle.", exEn:"The timetable is at the stop."},
{de:"Gleis", article:"das", plural:"Gleise", en:"platform; track", type:"noun", theme:"travel", ex:"Der Zug fährt von Gleis 3 ab.", exEn:"The train leaves from platform 3."},
{de:"Abfahrt", article:"die", plural:"Abfahrten", en:"departure", type:"noun", theme:"travel", ex:"Die Abfahrt ist um 9.15 Uhr.", exEn:"Departure is at 9:15."},
{de:"Ankunft", article:"die", plural:"Ankünfte", en:"arrival", type:"noun", theme:"travel", ex:"Die Ankunft in Berlin ist um 12 Uhr.", exEn:"Arrival in Berlin is at 12 o'clock."},
{de:"Verspätung", article:"die", plural:"Verspätungen", en:"delay", type:"noun", theme:"travel", ex:"Der Bus hat zehn Minuten Verspätung.", exEn:"The bus is ten minutes late."},
{de:"Reise", article:"die", plural:"Reisen", en:"journey; trip", type:"noun", theme:"travel", ex:"Die Reise dauert drei Stunden.", exEn:"The journey takes three hours."},
{de:"Urlaub", article:"der", plural:"Urlaube", en:"holiday; vacation", type:"noun", theme:"travel", ex:"Im August mache ich Urlaub.", exEn:"In August I'm going on holiday."},
{de:"Koffer", article:"der", plural:"Koffer", en:"suitcase", type:"noun", theme:"travel", ex:"Mein Koffer ist sehr schwer.", exEn:"My suitcase is very heavy."},
{de:"Tasche", article:"die", plural:"Taschen", en:"bag; pocket", type:"noun", theme:"travel", ex:"Meine Tasche ist grün.", exEn:"My bag is green."},
{de:"Gepäck", article:"das", plural:"—", en:"luggage", type:"noun", theme:"travel", ex:"Wo ist Ihr Gepäck?", exEn:"Where is your luggage?"},
{de:"Pass", article:"der", plural:"Pässe", en:"passport", type:"noun", theme:"travel", ex:"Hier ist mein Pass.", exEn:"Here is my passport."},
{de:"Ausweis", article:"der", plural:"Ausweise", en:"ID card", type:"noun", theme:"travel", ex:"Kann ich bitte Ihren Ausweis sehen?", exEn:"Can I see your ID, please?"},
{de:"Meer", article:"das", plural:"Meere", en:"sea", type:"noun", theme:"travel", ex:"Im Sommer fahren wir ans Meer.", exEn:"In summer we go to the seaside."},
{de:"See", article:"der", plural:"Seen", en:"lake", type:"noun", theme:"travel", ex:"Wir schwimmen im See.", exEn:"We swim in the lake."},
{de:"Strand", article:"der", plural:"Strände", en:"beach", type:"noun", theme:"travel", ex:"Der Strand ist sehr schön.", exEn:"The beach is very beautiful."},
{de:"Berg", article:"der", plural:"Berge", en:"mountain", type:"noun", theme:"travel", ex:"Der Berg ist sehr hoch.", exEn:"The mountain is very high."},
{de:"Ausland", article:"das", plural:"—", en:"abroad; foreign countries", type:"noun", theme:"travel", ex:"Mein Bruder arbeitet im Ausland.", exEn:"My brother works abroad."},
{de:"Information", article:"die", plural:"Informationen", en:"information", type:"noun", theme:"travel", ex:"Hier gibt es Informationen für Touristen.", exEn:"There is information for tourists here."},
{de:"Karte", article:"die", plural:"Karten", en:"card; map; ticket", type:"noun", theme:"travel", ex:"Ich schreibe dir eine Karte aus dem Urlaub.", exEn:"I'll write you a card from my holiday."},
{de:"Einzelzimmer", article:"das", plural:"Einzelzimmer", en:"single room", type:"noun", theme:"travel", ex:"Ein Einzelzimmer kostet 70 Euro.", exEn:"A single room costs 70 euros."},
{de:"Doppelzimmer", article:"das", plural:"Doppelzimmer", en:"double room", type:"noun", theme:"travel", ex:"Ich möchte ein Doppelzimmer für zwei Nächte.", exEn:"I'd like a double room for two nights."},
{de:"fahren", en:"to go (by vehicle); to drive", type:"verb", theme:"travel", ex:"Fährst du mit dem Auto?", exEn:"Are you going by car?"},
{de:"fliegen", en:"to fly", type:"verb", theme:"travel", ex:"Wir fliegen nach Spanien.", exEn:"We're flying to Spain."},
{de:"gehen", en:"to go; to walk", type:"verb", theme:"travel", ex:"Wir gehen zu Fuß.", exEn:"We're walking."},
{de:"laufen", en:"to run; to walk", type:"verb", theme:"travel", ex:"Die Kinder laufen in den Park.", exEn:"The children run into the park."},
{de:"reisen", en:"to travel", type:"verb", theme:"travel", ex:"Ich reise gern.", exEn:"I like travelling."},
{de:"abfahren", en:"to depart", type:"verb", theme:"travel", ex:"Der Bus fährt um 7 Uhr ab.", exEn:"The bus departs at 7 o'clock."},
{de:"ankommen", en:"to arrive", type:"verb", theme:"travel", ex:"Wann kommt der Zug an?", exEn:"When does the train arrive?"},
{de:"umsteigen", en:"to change (trains etc.)", type:"verb", theme:"travel", ex:"Sie müssen in Köln umsteigen.", exEn:"You have to change in Cologne."},
{de:"einsteigen", en:"to get on / in", type:"verb", theme:"travel", ex:"Bitte schnell einsteigen!", exEn:"Please get on quickly!"},
{de:"aussteigen", en:"to get off / out", type:"verb", theme:"travel", ex:"Ich steige an der nächsten Haltestelle aus.", exEn:"I'm getting off at the next stop."},
{de:"besuchen", en:"to visit", type:"verb", theme:"travel", ex:"Am Wochenende besuche ich meine Eltern.", exEn:"At the weekend I'm visiting my parents."},
{de:"übernachten", en:"to stay overnight", type:"verb", theme:"travel", ex:"Wir übernachten in einem Hotel.", exEn:"We're staying the night in a hotel."},

// ───────── Shopping & clothes ─────────
{de:"Geschäft", article:"das", plural:"Geschäfte", en:"shop; business", type:"noun", theme:"shopping", ex:"Das Geschäft ist neu.", exEn:"The shop is new."},
{de:"Laden", article:"der", plural:"Läden", en:"shop; store", type:"noun", theme:"shopping", ex:"Der Laden hat Obst und Gemüse.", exEn:"The shop has fruit and vegetables."},
{de:"Supermarkt", article:"der", plural:"Supermärkte", en:"supermarket", type:"noun", theme:"shopping", ex:"Ich gehe in den Supermarkt.", exEn:"I'm going to the supermarket."},
{de:"Preis", article:"der", plural:"Preise", en:"price", type:"noun", theme:"shopping", ex:"Der Preis ist gut.", exEn:"The price is good."},
{de:"Geld", article:"das", plural:"—", en:"money", type:"noun", theme:"shopping", ex:"Ich habe kein Geld.", exEn:"I have no money."},
{de:"Euro", article:"der", plural:"Euros", en:"euro", type:"noun", theme:"shopping", ex:"Das kostet zehn Euro.", exEn:"That costs ten euros."},
{de:"Cent", article:"der", plural:"Cents", en:"cent", type:"noun", theme:"shopping", ex:"Das Brötchen kostet 50 Cent.", exEn:"The roll costs 50 cents."},
{de:"Kasse", article:"die", plural:"Kassen", en:"checkout; till", type:"noun", theme:"shopping", ex:"Bitte zahlen Sie an der Kasse.", exEn:"Please pay at the checkout."},
{de:"Kreditkarte", article:"die", plural:"Kreditkarten", en:"credit card", type:"noun", theme:"shopping", ex:"Kann ich mit Kreditkarte bezahlen?", exEn:"Can I pay by credit card?"},
{de:"Angebot", article:"das", plural:"Angebote", en:"offer; special offer", type:"noun", theme:"shopping", ex:"Die Äpfel sind heute im Angebot.", exEn:"The apples are on offer today."},
{de:"Größe", article:"die", plural:"Größen", en:"size; height", type:"noun", theme:"shopping", ex:"Welche Größe haben Sie?", exEn:"What size are you?"},
{de:"Öffnungszeit", article:"die", plural:"Öffnungszeiten", en:"opening time", type:"noun", theme:"shopping", ex:"Wie sind die Öffnungszeiten?", exEn:"What are the opening hours?"},
{de:"Kleidung", article:"die", plural:"—", en:"clothes; clothing", type:"noun", theme:"shopping", ex:"Ich kaufe neue Kleidung.", exEn:"I'm buying new clothes."},
{de:"Hose", article:"die", plural:"Hosen", en:"trousers", type:"noun", theme:"shopping", ex:"Die Hose ist zu lang.", exEn:"The trousers are too long."},
{de:"Hemd", article:"das", plural:"Hemden", en:"shirt", type:"noun", theme:"shopping", ex:"Er trägt ein weißes Hemd.", exEn:"He is wearing a white shirt."},
{de:"T-Shirt", article:"das", plural:"T-Shirts", en:"T-shirt", type:"noun", theme:"shopping", ex:"Im Sommer trage ich T-Shirts.", exEn:"In summer I wear T-shirts."},
{de:"Pullover", article:"der", plural:"Pullover", en:"jumper; sweater", type:"noun", theme:"shopping", ex:"Der Pullover ist warm.", exEn:"The jumper is warm."},
{de:"Jacke", article:"die", plural:"Jacken", en:"jacket", type:"noun", theme:"shopping", ex:"Nimm eine Jacke mit!", exEn:"Take a jacket with you!"},
{de:"Mantel", article:"der", plural:"Mäntel", en:"coat", type:"noun", theme:"shopping", ex:"Im Winter trage ich einen Mantel.", exEn:"In winter I wear a coat."},
{de:"Kleid", article:"das", plural:"Kleider", en:"dress", type:"noun", theme:"shopping", ex:"Das Kleid ist sehr schön.", exEn:"The dress is very beautiful."},
{de:"Schuh", article:"der", plural:"Schuhe", en:"shoe", type:"noun", theme:"shopping", ex:"Die Schuhe sind zu klein.", exEn:"The shoes are too small."},
{de:"Brille", article:"die", plural:"Brillen", en:"glasses", type:"noun", theme:"shopping", ex:"Ich brauche eine Brille zum Lesen.", exEn:"I need glasses for reading."},
{de:"kaufen", en:"to buy", type:"verb", theme:"shopping", ex:"Ich kaufe Brot und Milch.", exEn:"I'm buying bread and milk."},
{de:"einkaufen", en:"to go shopping", type:"verb", theme:"shopping", ex:"Am Samstag kaufe ich ein.", exEn:"On Saturday I go shopping."},
{de:"kosten", en:"to cost", type:"verb", theme:"shopping", ex:"Wie viel kostet der Pullover?", exEn:"How much is the jumper?"},
{de:"anprobieren", en:"to try on", type:"verb", theme:"shopping", ex:"Kann ich die Hose anprobieren?", exEn:"Can I try on the trousers?"},
{de:"tragen", en:"to wear; to carry", type:"verb", theme:"shopping", ex:"Er trägt eine Brille.", exEn:"He wears glasses."},
{de:"anziehen", en:"to put on (clothes)", type:"verb", theme:"shopping", ex:"Ich ziehe meine Jacke an.", exEn:"I'm putting on my jacket."},
{de:"passen", en:"to fit; to suit", type:"verb", theme:"shopping", ex:"Die Hose passt mir nicht.", exEn:"The trousers don't fit me."},
{de:"brauchen", en:"to need", type:"verb", theme:"shopping", ex:"Ich brauche einen Kuli.", exEn:"I need a pen."},
{de:"billig", en:"cheap", type:"adjective", theme:"shopping", ex:"Die Schuhe sind billig.", exEn:"The shoes are cheap."},
{de:"teuer", en:"expensive", type:"adjective", theme:"shopping", ex:"Das Auto ist zu teuer.", exEn:"The car is too expensive."},
{de:"günstig", en:"good value; inexpensive", type:"adjective", theme:"shopping", ex:"Das Hotel ist günstig.", exEn:"The hotel is good value."},
{de:"geöffnet", en:"open (shop)", type:"adjective", theme:"shopping", ex:"Die Apotheke ist bis 20 Uhr geöffnet.", exEn:"The pharmacy is open until 8 pm."},
{de:"geschlossen", en:"closed", type:"adjective", theme:"shopping", ex:"Der Laden ist sonntags geschlossen.", exEn:"The shop is closed on Sundays."},

// ───────── Work ─────────
{de:"Arbeit", article:"die", plural:"Arbeiten", en:"work; job", type:"noun", theme:"work", ex:"Die Arbeit beginnt um acht Uhr.", exEn:"Work starts at eight o'clock."},
{de:"Beruf", article:"der", plural:"Berufe", en:"profession; job", type:"noun", theme:"work", ex:"Was sind Sie von Beruf?", exEn:"What do you do for a living?"},
{de:"Firma", article:"die", plural:"Firmen", en:"company; firm", type:"noun", theme:"work", ex:"Ich arbeite bei einer großen Firma.", exEn:"I work for a big company."},
{de:"Büro", article:"das", plural:"Büros", en:"office", type:"noun", theme:"work", ex:"Mein Büro ist im dritten Stock.", exEn:"My office is on the third floor."},
{de:"Chef", article:"der", plural:"Chefs", en:"boss (male)", type:"noun", theme:"work", ex:"Mein Chef ist sehr nett.", exEn:"My boss is very nice."},
{de:"Kollege", article:"der", plural:"Kollegen", en:"colleague (male)", type:"noun", theme:"work", ex:"Mein Kollege kommt aus Polen.", exEn:"My colleague comes from Poland."},
{de:"Koch", article:"der", plural:"Köche", en:"cook; chef", type:"noun", theme:"work", ex:"Der Koch arbeitet im Restaurant.", exEn:"The cook works in the restaurant."},
{de:"Verkäufer", article:"der", plural:"Verkäufer", en:"shop assistant (male)", type:"noun", theme:"work", ex:"Der Verkäufer ist freundlich.", exEn:"The shop assistant is friendly."},
{de:"Job", article:"der", plural:"Jobs", en:"job", type:"noun", theme:"work", ex:"Ich suche einen neuen Job.", exEn:"I'm looking for a new job."},
{de:"Stelle", article:"die", plural:"Stellen", en:"position; job; place", type:"noun", theme:"work", ex:"Die Stelle ist in München.", exEn:"The job is in Munich."},
{de:"Pause", article:"die", plural:"Pausen", en:"break", type:"noun", theme:"work", ex:"Wir machen eine Pause.", exEn:"We're taking a break."},
{de:"Computer", article:"der", plural:"Computer", en:"computer", type:"noun", theme:"work", ex:"Ich arbeite viel am Computer.", exEn:"I work a lot on the computer."},
{de:"Formular", article:"das", plural:"Formulare", en:"form", type:"noun", theme:"work", ex:"Bitte füllen Sie das Formular aus.", exEn:"Please fill in the form."},
{de:"Problem", article:"das", plural:"Probleme", en:"problem", type:"noun", theme:"work", ex:"Ich habe ein Problem mit dem Computer.", exEn:"I have a problem with the computer."},
{de:"Idee", article:"die", plural:"Ideen", en:"idea", type:"noun", theme:"work", ex:"Das ist eine gute Idee.", exEn:"That's a good idea."},
{de:"arbeiten", en:"to work", type:"verb", theme:"work", ex:"Ich arbeite in einem Krankenhaus.", exEn:"I work in a hospital."},
{de:"ausfüllen", en:"to fill in (a form)", type:"verb", theme:"work", ex:"Ich fülle das Formular aus.", exEn:"I'm filling in the form."},
{de:"unterschreiben", en:"to sign", type:"verb", theme:"work", ex:"Bitte unterschreiben Sie hier.", exEn:"Please sign here."},
{de:"telefonieren", en:"to phone; to be on the phone", type:"verb", theme:"work", ex:"Er telefoniert mit seiner Mutter.", exEn:"He is on the phone with his mother."},
{de:"anrufen", en:"to call (phone)", type:"verb", theme:"work", ex:"Ich rufe dich morgen an.", exEn:"I'll call you tomorrow."},
{de:"schicken", en:"to send", type:"verb", theme:"work", ex:"Ich schicke dir ein Foto.", exEn:"I'll send you a photo."},

// ───────── School & learning ─────────
{de:"Schule", article:"die", plural:"Schulen", en:"school", type:"noun", theme:"school", ex:"Die Kinder gehen in die Schule.", exEn:"The children go to school."},
{de:"Kurs", article:"der", plural:"Kurse", en:"course", type:"noun", theme:"school", ex:"Der Deutschkurs beginnt im Mai.", exEn:"The German course starts in May."},
{de:"Unterricht", article:"der", plural:"—", en:"lessons; class", type:"noun", theme:"school", ex:"Nach dem Unterricht gehe ich nach Hause.", exEn:"After class I go home."},
{de:"Klasse", article:"die", plural:"Klassen", en:"class; school year", type:"noun", theme:"school", ex:"In meiner Klasse sind 15 Schüler.", exEn:"There are 15 pupils in my class."},
{de:"Lehrer", article:"der", plural:"Lehrer", en:"teacher (male)", type:"noun", theme:"school", ex:"Der Lehrer erklärt die Grammatik.", exEn:"The teacher explains the grammar."},
{de:"Student", article:"der", plural:"Studenten", en:"student (male)", type:"noun", theme:"school", ex:"Er ist Student in Berlin.", exEn:"He is a student in Berlin."},
{de:"Schüler", article:"der", plural:"Schüler", en:"pupil (male)", type:"noun", theme:"school", ex:"Der Schüler macht Hausaufgaben.", exEn:"The pupil is doing homework."},
{de:"Prüfung", article:"die", plural:"Prüfungen", en:"exam", type:"noun", theme:"school", ex:"Die Prüfung ist am Freitag.", exEn:"The exam is on Friday."},
{de:"Hausaufgabe", article:"die", plural:"Hausaufgaben", en:"homework (task)", type:"noun", theme:"school", ex:"Hast du die Hausaufgaben gemacht?", exEn:"Have you done the homework?"},
{de:"Frage", article:"die", plural:"Fragen", en:"question", type:"noun", theme:"school", ex:"Ich habe eine Frage.", exEn:"I have a question."},
{de:"Antwort", article:"die", plural:"Antworten", en:"answer", type:"noun", theme:"school", ex:"Die Antwort ist richtig.", exEn:"The answer is correct."},
{de:"Wort", article:"das", plural:"Wörter", en:"word", type:"noun", theme:"school", ex:"Wie schreibt man das Wort?", exEn:"How do you spell the word?"},
{de:"Satz", article:"der", plural:"Sätze", en:"sentence", type:"noun", theme:"school", ex:"Lesen Sie den Satz.", exEn:"Read the sentence."},
{de:"Text", article:"der", plural:"Texte", en:"text", type:"noun", theme:"school", ex:"Der Text ist kurz.", exEn:"The text is short."},
{de:"Heft", article:"das", plural:"Hefte", en:"exercise book", type:"noun", theme:"school", ex:"Schreiben Sie die Wörter ins Heft.", exEn:"Write the words in your exercise book."},
{de:"Kuli", article:"der", plural:"Kulis", en:"(ballpoint) pen", type:"noun", theme:"school", ex:"Hast du einen Kuli für mich?", exEn:"Do you have a pen for me?"},
{de:"Papier", article:"das", plural:"Papiere", en:"paper", type:"noun", theme:"school", ex:"Ich brauche ein Blatt Papier.", exEn:"I need a sheet of paper."},
{de:"Seite", article:"die", plural:"Seiten", en:"page; side", type:"noun", theme:"school", ex:"Öffnen Sie das Buch auf Seite 20.", exEn:"Open the book at page 20."},
{de:"Übung", article:"die", plural:"Übungen", en:"exercise", type:"noun", theme:"school", ex:"Machen Sie bitte Übung 3.", exEn:"Please do exercise 3."},
{de:"Fehler", article:"der", plural:"Fehler", en:"mistake", type:"noun", theme:"school", ex:"Der Text hat viele Fehler.", exEn:"The text has many mistakes."},
{de:"lernen", en:"to learn; to study", type:"verb", theme:"school", ex:"Ich lerne Deutsch.", exEn:"I'm learning German."},
{de:"studieren", en:"to study (at university)", type:"verb", theme:"school", ex:"Er studiert Medizin.", exEn:"He studies medicine."},
{de:"schreiben", en:"to write", type:"verb", theme:"school", ex:"Schreiben Sie Ihren Namen hier.", exEn:"Write your name here."},
{de:"lesen", en:"to read", type:"verb", theme:"school", ex:"Ich lese gern Bücher.", exEn:"I like reading books."},
{de:"verstehen", en:"to understand", type:"verb", theme:"school", ex:"Verstehst du mich?", exEn:"Do you understand me?"},
{de:"fragen", en:"to ask", type:"verb", theme:"school", ex:"Darf ich etwas fragen?", exEn:"May I ask something?"},
{de:"antworten", en:"to answer", type:"verb", theme:"school", ex:"Bitte antworten Sie schnell.", exEn:"Please answer quickly."},
{de:"wiederholen", en:"to repeat", type:"verb", theme:"school", ex:"Können Sie das bitte wiederholen?", exEn:"Can you repeat that, please?"},
{de:"erklären", en:"to explain", type:"verb", theme:"school", ex:"Kannst du mir das erklären?", exEn:"Can you explain that to me?"},
{de:"üben", en:"to practise", type:"verb", theme:"school", ex:"Wir üben die Zahlen.", exEn:"We're practising the numbers."},
{de:"buchstabieren", en:"to spell", type:"verb", theme:"school", ex:"Können Sie Ihren Namen buchstabieren?", exEn:"Can you spell your name?"},

// ───────── Time & dates ─────────
{de:"Zeit", article:"die", plural:"Zeiten", en:"time", type:"noun", theme:"time", ex:"Hast du morgen Zeit?", exEn:"Do you have time tomorrow?"},
{de:"Stunde", article:"die", plural:"Stunden", en:"hour; lesson", type:"noun", theme:"time", ex:"Der Kurs dauert zwei Stunden.", exEn:"The course lasts two hours."},
{de:"Minute", article:"die", plural:"Minuten", en:"minute", type:"noun", theme:"time", ex:"Der Bus kommt in fünf Minuten.", exEn:"The bus is coming in five minutes."},
{de:"Tag", article:"der", plural:"Tage", en:"day", type:"noun", theme:"time", ex:"Ich arbeite acht Stunden am Tag.", exEn:"I work eight hours a day."},
{de:"Woche", article:"die", plural:"Wochen", en:"week", type:"noun", theme:"time", ex:"Ich habe drei Wochen Urlaub.", exEn:"I have three weeks' holiday."},
{de:"Monat", article:"der", plural:"Monate", en:"month", type:"noun", theme:"time", ex:"Die Miete zahle ich jeden Monat.", exEn:"I pay the rent every month."},
{de:"Jahr", article:"das", plural:"Jahre", en:"year", type:"noun", theme:"time", ex:"Ich lerne seit einem Jahr Deutsch.", exEn:"I have been learning German for a year."},
{de:"Wochenende", article:"das", plural:"Wochenenden", en:"weekend", type:"noun", theme:"time", ex:"Was machst du am Wochenende?", exEn:"What are you doing at the weekend?"},
{de:"Morgen", article:"der", plural:"Morgen", en:"morning", type:"noun", theme:"time", ex:"Am Morgen trinke ich Kaffee.", exEn:"In the morning I drink coffee."},
{de:"Mittag", article:"der", plural:"Mittage", en:"midday; noon", type:"noun", theme:"time", ex:"Am Mittag esse ich eine Suppe.", exEn:"At midday I have a soup."},
{de:"Nachmittag", article:"der", plural:"Nachmittage", en:"afternoon", type:"noun", theme:"time", ex:"Am Nachmittag gehe ich spazieren.", exEn:"In the afternoon I go for a walk."},
{de:"Abend", article:"der", plural:"Abende", en:"evening", type:"noun", theme:"time", ex:"Am Abend esse ich mit meiner Familie.", exEn:"In the evening I eat with my family."},
{de:"Nacht", article:"die", plural:"Nächte", en:"night", type:"noun", theme:"time", ex:"Gestern Nacht war es sehr kalt.", exEn:"Last night it was very cold."},
{de:"Montag", article:"der", plural:"Montage", en:"Monday", type:"noun", theme:"time", ex:"Am Montag gehe ich zum Deutschkurs.", exEn:"On Monday I go to my German course."},
{de:"Dienstag", article:"der", plural:"Dienstage", en:"Tuesday", type:"noun", theme:"time", ex:"Am Dienstag habe ich einen Termin.", exEn:"On Tuesday I have an appointment."},
{de:"Mittwoch", article:"der", plural:"Mittwoche", en:"Wednesday", type:"noun", theme:"time", ex:"Der Markt ist am Mittwoch.", exEn:"The market is on Wednesday."},
{de:"Donnerstag", article:"der", plural:"Donnerstage", en:"Thursday", type:"noun", theme:"time", ex:"Am Donnerstag gehe ich schwimmen.", exEn:"On Thursday I go swimming."},
{de:"Freitag", article:"der", plural:"Freitage", en:"Friday", type:"noun", theme:"time", ex:"Am Freitag gehen wir tanzen.", exEn:"On Friday we're going dancing."},
{de:"Samstag", article:"der", plural:"Samstage", en:"Saturday", type:"noun", theme:"time", ex:"Am Samstag habe ich frei.", exEn:"On Saturday I'm off."},
{de:"Sonntag", article:"der", plural:"Sonntage", en:"Sunday", type:"noun", theme:"time", ex:"Am Sonntag schlafe ich lange.", exEn:"On Sunday I sleep in."},
{de:"Januar", article:"der", plural:"Januare", en:"January", type:"noun", theme:"time", ex:"Im Januar ist es kalt.", exEn:"It's cold in January."},
{de:"Februar", article:"der", plural:"Februare", en:"February", type:"noun", theme:"time", ex:"Mein Geburtstag ist im Februar.", exEn:"My birthday is in February."},
{de:"März", article:"der", plural:"Märze", en:"March", type:"noun", theme:"time", ex:"Im März beginnt der Frühling.", exEn:"Spring begins in March."},
{de:"April", article:"der", plural:"Aprile", en:"April", type:"noun", theme:"time", ex:"Im April regnet es oft.", exEn:"It often rains in April."},
{de:"Mai", article:"der", plural:"Maie", en:"May", type:"noun", theme:"time", ex:"Im Mai ist es schon warm.", exEn:"In May it's already warm."},
{de:"Juni", article:"der", plural:"Junis", en:"June", type:"noun", theme:"time", ex:"Im Juni sind die Tage lang.", exEn:"In June the days are long."},
{de:"Juli", article:"der", plural:"Julis", en:"July", type:"noun", theme:"time", ex:"Im Juli fahren wir ans Meer.", exEn:"In July we go to the seaside."},
{de:"August", article:"der", plural:"Auguste", en:"August", type:"noun", theme:"time", ex:"Im August ist es heiß.", exEn:"It's hot in August."},
{de:"September", article:"der", plural:"September", en:"September", type:"noun", theme:"time", ex:"Im September beginnt die Schule.", exEn:"School starts in September."},
{de:"Oktober", article:"der", plural:"Oktober", en:"October", type:"noun", theme:"time", ex:"Der Oktober ist oft windig.", exEn:"October is often windy."},
{de:"November", article:"der", plural:"November", en:"November", type:"noun", theme:"time", ex:"Im November ist es oft grau.", exEn:"It's often grey in November."},
{de:"Dezember", article:"der", plural:"Dezember", en:"December", type:"noun", theme:"time", ex:"Im Dezember feiern wir Weihnachten.", exEn:"In December we celebrate Christmas."},
{de:"Frühling", article:"der", plural:"Frühlinge", en:"spring", type:"noun", theme:"time", ex:"Im Frühling ist es warm.", exEn:"It's warm in spring."},
{de:"Sommer", article:"der", plural:"Sommer", en:"summer", type:"noun", theme:"time", ex:"Im Sommer gehen wir schwimmen.", exEn:"In summer we go swimming."},
{de:"Herbst", article:"der", plural:"Herbste", en:"autumn", type:"noun", theme:"time", ex:"Im Herbst regnet es viel.", exEn:"It rains a lot in autumn."},
{de:"Winter", article:"der", plural:"Winter", en:"winter", type:"noun", theme:"time", ex:"Der Winter ist lang.", exEn:"The winter is long."},
{de:"Datum", article:"das", plural:"Daten", en:"date", type:"noun", theme:"time", ex:"Welches Datum ist heute?", exEn:"What's the date today?"},
{de:"Termin", article:"der", plural:"Termine", en:"appointment", type:"noun", theme:"time", ex:"Ich habe um zehn Uhr einen Termin beim Arzt.", exEn:"I have a doctor's appointment at ten."},
{de:"Uhrzeit", article:"die", plural:"Uhrzeiten", en:"time (of day)", type:"noun", theme:"time", ex:"Um welche Uhrzeit beginnt der Film?", exEn:"What time does the film start?"},
{de:"Ferien", article:"die", plural:"Pl.", en:"holidays (school)", type:"noun", theme:"time", ex:"In den Ferien fahren wir nach Italien.", exEn:"In the holidays we're going to Italy."},
{de:"Viertel", article:"das", plural:"Viertel", en:"quarter", type:"noun", theme:"time", ex:"Es ist Viertel nach drei.", exEn:"It's quarter past three."},
{de:"halb", en:"half (halb acht = 7:30)", type:"adjective", theme:"time", ex:"Es ist halb acht.", exEn:"It's half past seven."},
{de:"heute", en:"today", type:"adverb", theme:"time", ex:"Heute ist Montag.", exEn:"Today is Monday."},
{de:"morgen", en:"tomorrow", type:"adverb", theme:"time", ex:"Morgen habe ich frei.", exEn:"Tomorrow I'm off."},
{de:"gestern", en:"yesterday", type:"adverb", theme:"time", ex:"Gestern war ich im Kino.", exEn:"Yesterday I was at the cinema."},
{de:"jetzt", en:"now", type:"adverb", theme:"time", ex:"Ich habe jetzt keine Zeit.", exEn:"I don't have time now."},
{de:"bald", en:"soon", type:"adverb", theme:"time", ex:"Wir sehen uns bald.", exEn:"See you soon."},
{de:"später", en:"later", type:"adverb", theme:"time", ex:"Ich rufe dich später an.", exEn:"I'll call you later."},
{de:"früh", en:"early", type:"adjective", theme:"time", ex:"Ich stehe früh auf.", exEn:"I get up early."},
{de:"spät", en:"late", type:"adjective", theme:"time", ex:"Es ist schon spät.", exEn:"It's already late."},
{de:"immer", en:"always", type:"adverb", theme:"time", ex:"Er kommt immer zu spät.", exEn:"He is always late."},
{de:"oft", en:"often", type:"adverb", theme:"time", ex:"Ich gehe oft ins Kino.", exEn:"I often go to the cinema."},
{de:"manchmal", en:"sometimes", type:"adverb", theme:"time", ex:"Manchmal koche ich für Freunde.", exEn:"Sometimes I cook for friends."},
{de:"nie", en:"never", type:"adverb", theme:"time", ex:"Ich trinke nie Alkohol.", exEn:"I never drink alcohol."},
{de:"schon", en:"already", type:"adverb", theme:"time", ex:"Bist du schon fertig?", exEn:"Are you already finished?"},
{de:"noch", en:"still; yet", type:"adverb", theme:"time", ex:"Er schläft noch.", exEn:"He is still sleeping."},
{de:"zuerst", en:"first (of all)", type:"adverb", theme:"time", ex:"Zuerst lese ich die Zeitung.", exEn:"First I read the newspaper."},
{de:"dann", en:"then", type:"adverb", theme:"time", ex:"Zuerst essen wir, dann gehen wir spazieren.", exEn:"First we eat, then we go for a walk."},
{de:"pünktlich", en:"punctual; on time", type:"adjective", theme:"time", ex:"Der Zug ist pünktlich.", exEn:"The train is on time."},
{de:"dauern", en:"to last; to take (time)", type:"verb", theme:"time", ex:"Wie lange dauert der Film?", exEn:"How long is the film?"},
{de:"beginnen", en:"to begin", type:"verb", theme:"time", ex:"Der Film beginnt um acht.", exEn:"The film starts at eight."},
{de:"anfangen", en:"to start", type:"verb", theme:"time", ex:"Wann fängt die Party an?", exEn:"When does the party start?"},
{de:"warten", en:"to wait", type:"verb", theme:"time", ex:"Ich warte auf den Bus.", exEn:"I'm waiting for the bus."},

// ───────── Numbers ─────────
{de:"null", en:"zero", type:"number", theme:"numbers", ex:"Meine Telefonnummer beginnt mit null.", exEn:"My phone number starts with zero."},
{de:"eins", en:"one", type:"number", theme:"numbers", ex:"Eins plus eins ist zwei.", exEn:"One plus one is two."},
{de:"zwei", en:"two", type:"number", theme:"numbers", ex:"Wir haben zwei Katzen.", exEn:"We have two cats."},
{de:"drei", en:"three", type:"number", theme:"numbers", ex:"Das kostet drei Euro.", exEn:"That costs three euros."},
{de:"vier", en:"four", type:"number", theme:"numbers", ex:"Das Auto hat vier Türen.", exEn:"The car has four doors."},
{de:"fünf", en:"five", type:"number", theme:"numbers", ex:"Ich arbeite fünf Tage pro Woche.", exEn:"I work five days a week."},
{de:"sechs", en:"six", type:"number", theme:"numbers", ex:"Das Kind ist sechs Jahre alt.", exEn:"The child is six years old."},
{de:"sieben", en:"seven", type:"number", theme:"numbers", ex:"Die Woche hat sieben Tage.", exEn:"The week has seven days."},
{de:"acht", en:"eight", type:"number", theme:"numbers", ex:"Ich stehe um acht Uhr auf.", exEn:"I get up at eight o'clock."},
{de:"neun", en:"nine", type:"number", theme:"numbers", ex:"Mein Sohn ist neun.", exEn:"My son is nine."},
{de:"zehn", en:"ten", type:"number", theme:"numbers", ex:"Der Kurs hat zehn Teilnehmer.", exEn:"The course has ten participants."},
{de:"elf", en:"eleven", type:"number", theme:"numbers", ex:"Um elf Uhr trinken wir Kaffee.", exEn:"At eleven we have coffee."},
{de:"zwölf", en:"twelve", type:"number", theme:"numbers", ex:"Ein Jahr hat zwölf Monate.", exEn:"A year has twelve months."},
{de:"dreizehn", en:"thirteen", type:"number", theme:"numbers", ex:"Ich wohne in der Goethestraße 13.", exEn:"I live at 13 Goethestraße."},
{de:"fünfzehn", en:"fifteen", type:"number", theme:"numbers", ex:"Der Bus kommt in fünfzehn Minuten.", exEn:"The bus comes in fifteen minutes."},
{de:"sechzehn", en:"sixteen", type:"number", theme:"numbers", ex:"Meine Schwester ist sechzehn.", exEn:"My sister is sixteen."},
{de:"siebzehn", en:"seventeen", type:"number", theme:"numbers", ex:"Das Buch kostet siebzehn Euro.", exEn:"The book costs seventeen euros."},
{de:"zwanzig", en:"twenty", type:"number", theme:"numbers", ex:"In der Klasse sind zwanzig Schüler.", exEn:"There are twenty pupils in the class."},
{de:"einundzwanzig", en:"twenty-one", type:"number", theme:"numbers", ex:"Er ist einundzwanzig Jahre alt.", exEn:"He is twenty-one years old."},
{de:"dreißig", en:"thirty", type:"number", theme:"numbers", ex:"Heute sind es dreißig Grad.", exEn:"It's thirty degrees today."},
{de:"sechzig", en:"sixty", type:"number", theme:"numbers", ex:"Eine Stunde hat sechzig Minuten.", exEn:"An hour has sixty minutes."},
{de:"siebzig", en:"seventy", type:"number", theme:"numbers", ex:"Meine Oma ist siebzig.", exEn:"My grandma is seventy."},
{de:"hundert", en:"hundred", type:"number", theme:"numbers", ex:"Das Handy kostet hundert Euro.", exEn:"The phone costs a hundred euros."},
{de:"tausend", en:"thousand", type:"number", theme:"numbers", ex:"Das Dorf hat tausend Einwohner.", exEn:"The village has a thousand inhabitants."},
{de:"Million", article:"die", plural:"Millionen", en:"million", type:"noun", theme:"numbers", ex:"Berlin hat fast vier Millionen Einwohner.", exEn:"Berlin has almost four million inhabitants."},
{de:"erste", en:"first", type:"number", theme:"numbers", ex:"Das ist mein erster Tag im Kurs.", exEn:"This is my first day on the course."},
{de:"zweite", en:"second", type:"number", theme:"numbers", ex:"Wir wohnen im zweiten Stock.", exEn:"We live on the second floor."},
{de:"dritte", en:"third", type:"number", theme:"numbers", ex:"Heute ist der dritte Mai.", exEn:"Today is the third of May."},
{de:"Zahl", article:"die", plural:"Zahlen", en:"number; figure", type:"noun", theme:"numbers", ex:"Schreiben Sie die Zahlen.", exEn:"Write the numbers."},
{de:"Nummer", article:"die", plural:"Nummern", en:"number (phone, house)", type:"noun", theme:"numbers", ex:"Wie ist deine Nummer?", exEn:"What's your number?"},
{de:"einmal", en:"once", type:"adverb", theme:"numbers", ex:"Ich gehe einmal pro Woche schwimmen.", exEn:"I go swimming once a week."},

// ───────── Weather & nature ─────────
{de:"Wetter", article:"das", plural:"—", en:"weather", type:"noun", theme:"weather", ex:"Wie ist das Wetter heute?", exEn:"What's the weather like today?"},
{de:"Sonne", article:"die", plural:"Sonnen", en:"sun", type:"noun", theme:"weather", ex:"Die Sonne ist heute sehr stark.", exEn:"The sun is very strong today."},
{de:"Regen", article:"der", plural:"—", en:"rain", type:"noun", theme:"weather", ex:"Morgen kommt Regen.", exEn:"Rain is coming tomorrow."},
{de:"Schnee", article:"der", plural:"—", en:"snow", type:"noun", theme:"weather", ex:"Die Kinder spielen im Schnee.", exEn:"The children are playing in the snow."},
{de:"Wind", article:"der", plural:"Winde", en:"wind", type:"noun", theme:"weather", ex:"Der Wind ist stark.", exEn:"The wind is strong."},
{de:"Wolke", article:"die", plural:"Wolken", en:"cloud", type:"noun", theme:"weather", ex:"Am Himmel sind viele Wolken.", exEn:"There are many clouds in the sky."},
{de:"Himmel", article:"der", plural:"Himmel", en:"sky; heaven", type:"noun", theme:"weather", ex:"Am Himmel fliegt ein Vogel.", exEn:"A bird is flying in the sky."},
{de:"Grad", article:"der", plural:"Grade", en:"degree", type:"noun", theme:"weather", ex:"Es sind minus fünf Grad.", exEn:"It's minus five degrees."},
{de:"Baum", article:"der", plural:"Bäume", en:"tree", type:"noun", theme:"weather", ex:"Vor dem Haus steht ein Baum.", exEn:"There's a tree in front of the house."},
{de:"Blume", article:"die", plural:"Blumen", en:"flower", type:"noun", theme:"weather", ex:"Ich kaufe Blumen für meine Mutter.", exEn:"I'm buying flowers for my mother."},
{de:"Tier", article:"das", plural:"Tiere", en:"animal", type:"noun", theme:"weather", ex:"Welches Tier magst du?", exEn:"Which animal do you like?"},
{de:"Hund", article:"der", plural:"Hunde", en:"dog", type:"noun", theme:"weather", ex:"Der Hund heißt Bello.", exEn:"The dog is called Bello."},
{de:"Katze", article:"die", plural:"Katzen", en:"cat", type:"noun", theme:"weather", ex:"Die Katze trinkt Milch.", exEn:"The cat is drinking milk."},
{de:"Vogel", article:"der", plural:"Vögel", en:"bird", type:"noun", theme:"weather", ex:"Der Vogel singt.", exEn:"The bird is singing."},
{de:"Wald", article:"der", plural:"Wälder", en:"forest; woods", type:"noun", theme:"weather", ex:"Wir gehen im Wald spazieren.", exEn:"We go for a walk in the woods."},
{de:"sonnig", en:"sunny", type:"adjective", theme:"weather", ex:"Morgen wird es sonnig.", exEn:"Tomorrow it will be sunny."},
{de:"warm", en:"warm", type:"adjective", theme:"weather", ex:"Heute ist es warm.", exEn:"It's warm today."},
{de:"kalt", en:"cold", type:"adjective", theme:"weather", ex:"Das Wasser ist kalt.", exEn:"The water is cold."},
{de:"heiß", en:"hot", type:"adjective", theme:"weather", ex:"Der Kaffee ist heiß.", exEn:"The coffee is hot."},
{de:"windig", en:"windy", type:"adjective", theme:"weather", ex:"Heute ist es sehr windig.", exEn:"It's very windy today."},
{de:"regnen", en:"to rain", type:"verb", theme:"weather", ex:"Es regnet schon den ganzen Tag.", exEn:"It has been raining all day."},
{de:"schneien", en:"to snow", type:"verb", theme:"weather", ex:"Im Dezember schneit es oft.", exEn:"It often snows in December."},
{de:"scheinen", en:"to shine", type:"verb", theme:"weather", ex:"Heute scheint die Sonne.", exEn:"The sun is shining today."},

// ───────── Leisure ─────────
{de:"Freizeit", article:"die", plural:"—", en:"free time", type:"noun", theme:"leisure", ex:"Was machst du in deiner Freizeit?", exEn:"What do you do in your free time?"},
{de:"Hobby", article:"das", plural:"Hobbys", en:"hobby", type:"noun", theme:"leisure", ex:"Mein Hobby ist Lesen.", exEn:"My hobby is reading."},
{de:"Sport", article:"der", plural:"—", en:"sport; exercise", type:"noun", theme:"leisure", ex:"Ich mache gern Sport.", exEn:"I like doing sport."},
{de:"Fußball", article:"der", plural:"Fußbälle", en:"football", type:"noun", theme:"leisure", ex:"Am Samstag spielen wir Fußball.", exEn:"On Saturday we play football."},
{de:"Spiel", article:"das", plural:"Spiele", en:"game; match", type:"noun", theme:"leisure", ex:"Das Spiel beginnt um 15 Uhr.", exEn:"The match starts at 3 pm."},
{de:"Musik", article:"die", plural:"—", en:"music", type:"noun", theme:"leisure", ex:"Ich höre gern Musik.", exEn:"I like listening to music."},
{de:"Konzert", article:"das", plural:"Konzerte", en:"concert", type:"noun", theme:"leisure", ex:"Wir gehen am Freitag ins Konzert.", exEn:"We're going to a concert on Friday."},
{de:"Film", article:"der", plural:"Filme", en:"film; movie", type:"noun", theme:"leisure", ex:"Der Film beginnt um 20 Uhr.", exEn:"The film starts at 8 pm."},
{de:"Foto", article:"das", plural:"Fotos", en:"photo", type:"noun", theme:"leisure", ex:"Ich mache ein Foto.", exEn:"I'm taking a photo."},
{de:"Party", article:"die", plural:"Partys", en:"party", type:"noun", theme:"leisure", ex:"Am Samstag mache ich eine Party.", exEn:"I'm having a party on Saturday."},
{de:"Einladung", article:"die", plural:"Einladungen", en:"invitation", type:"noun", theme:"leisure", ex:"Danke für die Einladung!", exEn:"Thanks for the invitation!"},
{de:"Geschenk", article:"das", plural:"Geschenke", en:"present; gift", type:"noun", theme:"leisure", ex:"Das Geschenk ist für dich.", exEn:"The present is for you."},
{de:"Schwimmbad", article:"das", plural:"Schwimmbäder", en:"swimming pool", type:"noun", theme:"leisure", ex:"Im Sommer gehen wir ins Schwimmbad.", exEn:"In summer we go to the swimming pool."},
{de:"Internet", article:"das", plural:"—", en:"internet", type:"noun", theme:"leisure", ex:"Ich suche die Information im Internet.", exEn:"I look for the information on the internet."},
{de:"Spaß", article:"der", plural:"Späße", en:"fun; joke", type:"noun", theme:"leisure", ex:"Deutsch lernen macht Spaß!", exEn:"Learning German is fun!"},
{de:"spielen", en:"to play", type:"verb", theme:"leisure", ex:"Die Kinder spielen im Garten.", exEn:"The children are playing in the garden."},
{de:"schwimmen", en:"to swim", type:"verb", theme:"leisure", ex:"Ich schwimme gern.", exEn:"I like swimming."},
{de:"tanzen", en:"to dance", type:"verb", theme:"leisure", ex:"Wir tanzen die ganze Nacht.", exEn:"We dance all night."},
{de:"singen", en:"to sing", type:"verb", theme:"leisure", ex:"Sie singt sehr schön.", exEn:"She sings very beautifully."},
{de:"wandern", en:"to hike", type:"verb", theme:"leisure", ex:"Am Wochenende wandern wir in den Bergen.", exEn:"At the weekend we go hiking in the mountains."},
{de:"spazieren gehen", en:"to go for a walk", type:"verb", theme:"leisure", ex:"Wir gehen im Park spazieren.", exEn:"We go for a walk in the park."},
{de:"Rad fahren", en:"to cycle", type:"verb", theme:"leisure", ex:"Ich fahre gern Rad.", exEn:"I like cycling."},
{de:"fernsehen", en:"to watch TV", type:"verb", theme:"leisure", ex:"Am Abend sehe ich fern.", exEn:"In the evening I watch TV."},
{de:"einladen", en:"to invite", type:"verb", theme:"leisure", ex:"Ich lade dich zum Essen ein.", exEn:"I'm inviting you for a meal."},
{de:"feiern", en:"to celebrate", type:"verb", theme:"leisure", ex:"Wir feiern meinen Geburtstag.", exEn:"We're celebrating my birthday."},
{de:"treffen", en:"to meet", type:"verb", theme:"leisure", ex:"Ich treffe meine Freunde im Café.", exEn:"I'm meeting my friends at the café."},
{de:"sehen", en:"to see", type:"verb", theme:"leisure", ex:"Siehst du das Haus dort?", exEn:"Can you see the house over there?"},
{de:"hören", en:"to hear; to listen to", type:"verb", theme:"leisure", ex:"Hörst du die Musik?", exEn:"Can you hear the music?"},

// ───────── Colours ─────────
{de:"Farbe", article:"die", plural:"Farben", en:"colour", type:"noun", theme:"colours", ex:"Welche Farbe hat dein Auto?", exEn:"What colour is your car?"},
{de:"rot", en:"red", type:"adjective", theme:"colours", ex:"Die Tomaten sind rot.", exEn:"The tomatoes are red."},
{de:"blau", en:"blue", type:"adjective", theme:"colours", ex:"Der Himmel ist blau.", exEn:"The sky is blue."},
{de:"grün", en:"green", type:"adjective", theme:"colours", ex:"Das Gras ist grün.", exEn:"The grass is green."},
{de:"gelb", en:"yellow", type:"adjective", theme:"colours", ex:"Die Banane ist gelb.", exEn:"The banana is yellow."},
{de:"schwarz", en:"black", type:"adjective", theme:"colours", ex:"Ich trinke den Kaffee schwarz.", exEn:"I drink my coffee black."},
{de:"weiß", en:"white", type:"adjective", theme:"colours", ex:"Der Schnee ist weiß.", exEn:"The snow is white."},
{de:"grau", en:"grey", type:"adjective", theme:"colours", ex:"Heute ist der Himmel grau.", exEn:"The sky is grey today."},
{de:"braun", en:"brown", type:"adjective", theme:"colours", ex:"Der Hund ist braun.", exEn:"The dog is brown."},
{de:"orange", en:"orange", type:"adjective", theme:"colours", ex:"Die Jacke ist orange.", exEn:"The jacket is orange."},
{de:"rosa", en:"pink", type:"adjective", theme:"colours", ex:"Das Kleid ist rosa.", exEn:"The dress is pink."},
{de:"bunt", en:"colourful", type:"adjective", theme:"colours", ex:"Die Bilder sind bunt.", exEn:"The pictures are colourful."},

// ───────── Everyday verbs ─────────
{de:"sein", en:"to be", type:"verb", theme:"everyday", ex:"Wir sind aus Italien.", exEn:"We are from Italy."},
{de:"haben", en:"to have", type:"verb", theme:"everyday", ex:"Ich habe einen Hund.", exEn:"I have a dog."},
{de:"werden", en:"to become", type:"verb", theme:"everyday", ex:"Ich werde bald 30.", exEn:"I'll be 30 soon."},
{de:"können", en:"can; to be able to", type:"verb", theme:"everyday", ex:"Kannst du schwimmen?", exEn:"Can you swim?"},
{de:"müssen", en:"must; to have to", type:"verb", theme:"everyday", ex:"Ich muss heute arbeiten.", exEn:"I have to work today."},
{de:"wollen", en:"to want", type:"verb", theme:"everyday", ex:"Ich will Deutsch lernen.", exEn:"I want to learn German."},
{de:"möchten", en:"would like", type:"verb", theme:"everyday", ex:"Ich möchte einen Kaffee.", exEn:"I would like a coffee."},
{de:"dürfen", en:"may; to be allowed to", type:"verb", theme:"everyday", ex:"Darf ich das Fenster öffnen?", exEn:"May I open the window?"},
{de:"sollen", en:"should; to be supposed to", type:"verb", theme:"everyday", ex:"Der Arzt sagt, ich soll viel trinken.", exEn:"The doctor says I should drink a lot."},
{de:"mögen", en:"to like", type:"verb", theme:"everyday", ex:"Ich mag Katzen.", exEn:"I like cats."},
{de:"machen", en:"to do; to make", type:"verb", theme:"everyday", ex:"Ich mache meine Hausaufgaben.", exEn:"I'm doing my homework."},
{de:"kommen", en:"to come", type:"verb", theme:"everyday", ex:"Wann kommst du nach Hause?", exEn:"When are you coming home?"},
{de:"mitkommen", en:"to come along", type:"verb", theme:"everyday", ex:"Kommst du mit ins Kino?", exEn:"Are you coming to the cinema with us?"},
{de:"sagen", en:"to say", type:"verb", theme:"everyday", ex:"Was sagst du?", exEn:"What are you saying?"},
{de:"sprechen", en:"to speak", type:"verb", theme:"everyday", ex:"Er spricht Englisch und Französisch.", exEn:"He speaks English and French."},
{de:"heißen", en:"to be called", type:"verb", theme:"everyday", ex:"Wie heißt du?", exEn:"What's your name?"},
{de:"leben", en:"to live", type:"verb", theme:"everyday", ex:"Wir leben seit zwei Jahren in Deutschland.", exEn:"We have been living in Germany for two years."},
{de:"geben", en:"to give", type:"verb", theme:"everyday", ex:"Gib mir bitte das Salz.", exEn:"Please pass me the salt."},
{de:"nehmen", en:"to take", type:"verb", theme:"everyday", ex:"Ich nehme den Fisch.", exEn:"I'll have the fish."},
{de:"bringen", en:"to bring", type:"verb", theme:"everyday", ex:"Der Kellner bringt die Suppe.", exEn:"The waiter brings the soup."},
{de:"abholen", en:"to pick up", type:"verb", theme:"everyday", ex:"Ich hole dich am Bahnhof ab.", exEn:"I'll pick you up at the station."},
{de:"finden", en:"to find; to think (opinion)", type:"verb", theme:"everyday", ex:"Ich finde den Film gut.", exEn:"I think the film is good."},
{de:"suchen", en:"to look for", type:"verb", theme:"everyday", ex:"Ich suche meine Brille.", exEn:"I'm looking for my glasses."},
{de:"wissen", en:"to know (a fact)", type:"verb", theme:"everyday", ex:"Weißt du, wo der Bahnhof ist?", exEn:"Do you know where the station is?"},
{de:"kennen", en:"to know (be familiar with)", type:"verb", theme:"everyday", ex:"Kennst du meinen Bruder?", exEn:"Do you know my brother?"},
{de:"denken", en:"to think", type:"verb", theme:"everyday", ex:"Ich denke oft an dich.", exEn:"I often think of you."},
{de:"glauben", en:"to believe; to think", type:"verb", theme:"everyday", ex:"Ich glaube, er ist krank.", exEn:"I think he is ill."},
{de:"gefallen", en:"to please; to like", type:"verb", theme:"everyday", ex:"Die Stadt gefällt mir.", exEn:"I like the city."},
{de:"helfen", en:"to help", type:"verb", theme:"everyday", ex:"Kannst du mir helfen?", exEn:"Can you help me?"},
{de:"zeigen", en:"to show", type:"verb", theme:"everyday", ex:"Ich zeige dir die Wohnung.", exEn:"I'll show you the flat."},
{de:"bleiben", en:"to stay", type:"verb", theme:"everyday", ex:"Ich bleibe drei Tage in Wien.", exEn:"I'm staying in Vienna for three days."},
{de:"liegen", en:"to lie; to be (lying)", type:"verb", theme:"everyday", ex:"Das Buch liegt auf dem Tisch.", exEn:"The book is on the table."},
{de:"stehen", en:"to stand", type:"verb", theme:"everyday", ex:"Das Auto steht vor dem Haus.", exEn:"The car is in front of the house."},
{de:"sitzen", en:"to sit", type:"verb", theme:"everyday", ex:"Wir sitzen im Garten.", exEn:"We're sitting in the garden."},
{de:"öffnen", en:"to open", type:"verb", theme:"everyday", ex:"Öffnen Sie bitte das Buch.", exEn:"Please open the book."},
{de:"schließen", en:"to close", type:"verb", theme:"everyday", ex:"Die Bank schließt um 16 Uhr.", exEn:"The bank closes at 4 pm."},
{de:"aufmachen", en:"to open", type:"verb", theme:"everyday", ex:"Mach bitte das Fenster auf.", exEn:"Please open the window."},
{de:"zumachen", en:"to close", type:"verb", theme:"everyday", ex:"Mach bitte die Tür zu.", exEn:"Please close the door."},
{de:"bekommen", en:"to get; to receive", type:"verb", theme:"everyday", ex:"Ich bekomme viele E-Mails.", exEn:"I get a lot of emails."},
{de:"vergessen", en:"to forget", type:"verb", theme:"everyday", ex:"Ich habe meinen Schlüssel vergessen.", exEn:"I've forgotten my key."},
{de:"erzählen", en:"to tell", type:"verb", theme:"everyday", ex:"Erzähl mal, wie war der Urlaub?", exEn:"Tell me, how was the holiday?"},
{de:"lieben", en:"to love", type:"verb", theme:"everyday", ex:"Ich liebe dich.", exEn:"I love you."},
{de:"sich freuen", en:"to be happy; to look forward", type:"verb", theme:"everyday", ex:"Ich freue mich auf das Wochenende.", exEn:"I'm looking forward to the weekend."},
{de:"gehören", en:"to belong", type:"verb", theme:"everyday", ex:"Gehört die Tasche dir?", exEn:"Does the bag belong to you?"},
{de:"benutzen", en:"to use", type:"verb", theme:"everyday", ex:"Darf ich dein Handy benutzen?", exEn:"May I use your phone?"},
{de:"rauchen", en:"to smoke", type:"verb", theme:"everyday", ex:"Hier darf man nicht rauchen.", exEn:"You're not allowed to smoke here."},

// ───────── Everyday adjectives ─────────
{de:"gut", en:"good; well", type:"adjective", theme:"everyday", ex:"Der Film ist sehr gut.", exEn:"The film is very good."},
{de:"schlecht", en:"bad", type:"adjective", theme:"everyday", ex:"Das Wetter ist schlecht.", exEn:"The weather is bad."},
{de:"schön", en:"beautiful; nice", type:"adjective", theme:"everyday", ex:"Die Stadt ist sehr schön.", exEn:"The city is very beautiful."},
{de:"groß", en:"big; tall", type:"adjective", theme:"everyday", ex:"Mein Bruder ist sehr groß.", exEn:"My brother is very tall."},
{de:"klein", en:"small; short", type:"adjective", theme:"everyday", ex:"Die Wohnung ist klein.", exEn:"The flat is small."},
{de:"lang", en:"long", type:"adjective", theme:"everyday", ex:"Der Weg ist sehr lang.", exEn:"The way is very long."},
{de:"kurz", en:"short", type:"adjective", theme:"everyday", ex:"Die Pause ist kurz.", exEn:"The break is short."},
{de:"alt", en:"old", type:"adjective", theme:"everyday", ex:"Das Haus ist sehr alt.", exEn:"The house is very old."},
{de:"jung", en:"young", type:"adjective", theme:"everyday", ex:"Meine Mutter ist noch jung.", exEn:"My mother is still young."},
{de:"neu", en:"new", type:"adjective", theme:"everyday", ex:"Ich habe ein neues Auto.", exEn:"I have a new car."},
{de:"schnell", en:"fast; quick", type:"adjective", theme:"everyday", ex:"Das Auto fährt sehr schnell.", exEn:"The car goes very fast."},
{de:"langsam", en:"slow; slowly", type:"adjective", theme:"everyday", ex:"Sprechen Sie bitte langsam.", exEn:"Please speak slowly."},
{de:"leicht", en:"easy; light", type:"adjective", theme:"everyday", ex:"Die Übung ist leicht.", exEn:"The exercise is easy."},
{de:"schwer", en:"heavy; difficult", type:"adjective", theme:"everyday", ex:"Deutsch ist nicht so schwer.", exEn:"German isn't that difficult."},
{de:"einfach", en:"simple; easy", type:"adjective", theme:"everyday", ex:"Das ist ganz einfach.", exEn:"That's really simple."},
{de:"richtig", en:"right; correct", type:"adjective", theme:"everyday", ex:"Das ist richtig!", exEn:"That's correct!"},
{de:"falsch", en:"wrong", type:"adjective", theme:"everyday", ex:"Die Antwort ist falsch.", exEn:"The answer is wrong."},
{de:"frei", en:"free; available", type:"adjective", theme:"everyday", ex:"Ist hier noch frei?", exEn:"Is this seat free?"},
{de:"besetzt", en:"occupied; engaged", type:"adjective", theme:"everyday", ex:"Die Toilette ist besetzt.", exEn:"The toilet is occupied."},
{de:"offen", en:"open", type:"adjective", theme:"everyday", ex:"Das Fenster ist offen.", exEn:"The window is open."},
{de:"voll", en:"full", type:"adjective", theme:"everyday", ex:"Der Bus ist voll.", exEn:"The bus is full."},
{de:"leer", en:"empty", type:"adjective", theme:"everyday", ex:"Die Flasche ist leer.", exEn:"The bottle is empty."},
{de:"glücklich", en:"happy", type:"adjective", theme:"everyday", ex:"Ich bin sehr glücklich.", exEn:"I am very happy."},
{de:"traurig", en:"sad", type:"adjective", theme:"everyday", ex:"Warum bist du traurig?", exEn:"Why are you sad?"},
{de:"nett", en:"nice; kind", type:"adjective", theme:"everyday", ex:"Deine Freundin ist sehr nett.", exEn:"Your friend is very nice."},
{de:"freundlich", en:"friendly", type:"adjective", theme:"everyday", ex:"Die Leute hier sind freundlich.", exEn:"The people here are friendly."},
{de:"lustig", en:"funny", type:"adjective", theme:"everyday", ex:"Mein Onkel ist sehr lustig.", exEn:"My uncle is very funny."},
{de:"interessant", en:"interesting", type:"adjective", theme:"everyday", ex:"Das Buch ist interessant.", exEn:"The book is interesting."},
{de:"langweilig", en:"boring", type:"adjective", theme:"everyday", ex:"Der Film ist langweilig.", exEn:"The film is boring."},
{de:"wichtig", en:"important", type:"adjective", theme:"everyday", ex:"Das ist sehr wichtig.", exEn:"That is very important."},
{de:"fertig", en:"ready; finished", type:"adjective", theme:"everyday", ex:"Ich bin gleich fertig.", exEn:"I'll be ready in a moment."},
{de:"kaputt", en:"broken", type:"adjective", theme:"everyday", ex:"Die Lampe ist kaputt.", exEn:"The lamp is broken."},
{de:"sauber", en:"clean", type:"adjective", theme:"everyday", ex:"Die Küche ist sauber.", exEn:"The kitchen is clean."},
{de:"schmutzig", en:"dirty", type:"adjective", theme:"everyday", ex:"Die Schuhe sind schmutzig.", exEn:"The shoes are dirty."},
{de:"toll", en:"great; fantastic", type:"adjective", theme:"everyday", ex:"Der Urlaub war toll!", exEn:"The holiday was great!"},
{de:"möglich", en:"possible", type:"adjective", theme:"everyday", ex:"Ist das möglich?", exEn:"Is that possible?"},
{de:"allein", en:"alone", type:"adjective", theme:"everyday", ex:"Ich wohne allein.", exEn:"I live alone."},
{de:"nächste", en:"next; nearest", type:"adjective", theme:"everyday", ex:"Wo ist die nächste Haltestelle?", exEn:"Where is the nearest stop?"},
{de:"viel", en:"a lot; much", type:"adjective", theme:"everyday", ex:"Ich habe viel Arbeit.", exEn:"I have a lot of work."},
{de:"wenig", en:"little; not much", type:"adjective", theme:"everyday", ex:"Ich habe wenig Zeit.", exEn:"I have little time."},

// ───────── Small everyday words ─────────
{de:"hier", en:"here", type:"adverb", theme:"everyday", ex:"Ich wohne hier.", exEn:"I live here."},
{de:"dort", en:"there", type:"adverb", theme:"everyday", ex:"Dort ist der Bahnhof.", exEn:"The station is over there."},
{de:"oben", en:"up; upstairs", type:"adverb", theme:"everyday", ex:"Das Schlafzimmer ist oben.", exEn:"The bedroom is upstairs."},
{de:"unten", en:"down; downstairs", type:"adverb", theme:"everyday", ex:"Die Küche ist unten.", exEn:"The kitchen is downstairs."},
{de:"sehr", en:"very", type:"adverb", theme:"everyday", ex:"Das ist sehr gut.", exEn:"That is very good."},
{de:"auch", en:"also; too", type:"adverb", theme:"everyday", ex:"Ich komme auch mit.", exEn:"I'm coming too."},
{de:"nur", en:"only", type:"adverb", theme:"everyday", ex:"Ich habe nur zehn Euro.", exEn:"I only have ten euros."},
{de:"nicht", en:"not", type:"adverb", theme:"everyday", ex:"Ich rauche nicht.", exEn:"I don't smoke."},
{de:"wieder", en:"again", type:"adverb", theme:"everyday", ex:"Wann kommst du wieder?", exEn:"When are you coming back?"},
{de:"zusammen", en:"together", type:"adverb", theme:"everyday", ex:"Wir kochen zusammen.", exEn:"We cook together."},
{de:"gleich", en:"right away; same", type:"adverb", theme:"everyday", ex:"Ich komme gleich.", exEn:"I'm coming right away."},
{de:"etwas", en:"something; a bit", type:"other", theme:"everyday", ex:"Möchtest du etwas trinken?", exEn:"Would you like something to drink?"},
{de:"nichts", en:"nothing", type:"other", theme:"everyday", ex:"Ich möchte nichts essen.", exEn:"I don't want to eat anything."},
{de:"alles", en:"everything", type:"other", theme:"everyday", ex:"Alles ist gut.", exEn:"Everything is fine."},
{de:"vielleicht", en:"maybe; perhaps", type:"adverb", theme:"everyday", ex:"Vielleicht komme ich morgen.", exEn:"Maybe I'll come tomorrow."},
{de:"leider", en:"unfortunately", type:"adverb", theme:"everyday", ex:"Ich habe leider keine Zeit.", exEn:"Unfortunately I don't have time."},
{de:"natürlich", en:"of course", type:"adverb", theme:"everyday", ex:"Natürlich helfe ich dir.", exEn:"Of course I'll help you."},
{de:"gern", en:"gladly; like to (do)", type:"adverb", theme:"everyday", ex:"Ich spiele gern Fußball.", exEn:"I like playing football."},
{de:"und", en:"and", type:"other", theme:"everyday", ex:"Ich trinke Kaffee und esse ein Brötchen.", exEn:"I drink coffee and eat a roll."},
{de:"oder", en:"or", type:"other", theme:"everyday", ex:"Tee oder Kaffee?", exEn:"Tea or coffee?"},
{de:"aber", en:"but", type:"other", theme:"everyday", ex:"Das Hotel ist schön, aber teuer.", exEn:"The hotel is nice but expensive."},
{de:"mit", en:"with; by (transport)", type:"other", theme:"everyday", ex:"Ich fahre mit dem Zug.", exEn:"I'm going by train."},
{de:"ohne", en:"without", type:"other", theme:"everyday", ex:"Ich trinke Kaffee ohne Zucker.", exEn:"I drink coffee without sugar."},
{de:"für", en:"for", type:"other", theme:"everyday", ex:"Die Blumen sind für dich.", exEn:"The flowers are for you."},
{de:"von", en:"from; of", type:"other", theme:"everyday", ex:"Das ist ein Brief von meiner Mutter.", exEn:"This is a letter from my mother."},
{de:"zu", en:"to; too", type:"other", theme:"everyday", ex:"Ich gehe zum Arzt.", exEn:"I'm going to the doctor."},
{de:"nach", en:"to (places); after", type:"other", theme:"everyday", ex:"Ich fahre nach Berlin.", exEn:"I'm going to Berlin."},
{de:"aus", en:"from; out of", type:"other", theme:"everyday", ex:"Ich komme aus der Türkei.", exEn:"I come from Turkey."},
{de:"bei", en:"at; with (someone's place)", type:"other", theme:"everyday", ex:"Ich wohne bei meinen Eltern.", exEn:"I live with my parents."},
{de:"um", en:"at (time); around", type:"other", theme:"everyday", ex:"Der Kurs beginnt um neun Uhr.", exEn:"The course starts at nine o'clock."},

// ───────── Question words ─────────
{de:"wer", en:"who", type:"question", theme:"everyday", ex:"Wer ist das?", exEn:"Who is that?"},
{de:"was", en:"what", type:"question", theme:"everyday", ex:"Was machst du heute?", exEn:"What are you doing today?"},
{de:"wo", en:"where", type:"question", theme:"everyday", ex:"Wo ist die Toilette?", exEn:"Where is the toilet?"},
{de:"woher", en:"where from", type:"question", theme:"everyday", ex:"Woher kommst du?", exEn:"Where are you from?"},
{de:"wohin", en:"where to", type:"question", theme:"everyday", ex:"Wohin fährst du im Urlaub?", exEn:"Where are you going on holiday?"},
{de:"wann", en:"when", type:"question", theme:"everyday", ex:"Wann beginnt der Kurs?", exEn:"When does the course start?"},
{de:"wie", en:"how", type:"question", theme:"everyday", ex:"Wie geht es dir?", exEn:"How are you?"},
{de:"warum", en:"why", type:"question", theme:"everyday", ex:"Warum lernst du Deutsch?", exEn:"Why are you learning German?"},
{de:"welcher", en:"which", type:"question", theme:"everyday", ex:"Welcher Bus fährt zum Bahnhof?", exEn:"Which bus goes to the station?"},
{de:"wie viel", en:"how much", type:"question", theme:"everyday", ex:"Wie viel Uhr ist es?", exEn:"What time is it?"},
{de:"wie viele", en:"how many", type:"question", theme:"everyday", ex:"Wie viele Geschwister hast du?", exEn:"How many siblings do you have?"},
];
